### ISSUE TITLE
Automathic labelling links / references

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#106]
It would be VERY useful if the system did an automatic labeling of the elements that link to other elements. At least, when there is a one-to-one relationship.

For example, a status dependency is linked to a single status report. Then the system could automatically label the status dependency with the basic info about the status report it is linked to (i.e.: Olivia Multi-Period-Daily.

Another equally useful case is that of data dependencies, which could be named after the data set they are linked to (i.e.: Olivia Candles).

Those two are the ones in which users are more prone to make mistakes and the ones you want to check when something in an indicator is not working. It could be extended to other cases as well.

**Comment by julian-molina** [comment]
Those fields in those particular elements should not be editable.

**Comment by Luis-Fernando-Molina** [comment]
done
