### ISSUE TITLE
Provide a way to filter out simulation layers from Products Panels

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [Superalgos/Superalgos#108]
The way for now to do that is by collapsing the Layer Manager object or any of its parents. If the individual layers are not visible at the designer, they wont be visible at the layers panel.

![image](https://user-images.githubusercontent.com/9479367/69899061-77bf4280-1361-11ea-9245-0a574ccdfca9.png)

**Comment by julian-molina** [comment]
I understand this may be a temporary solution, but in my experience, it will be VERY painful to work with several backtesting sessions at the same time if you need to keep both parameters and layers visible in the designer. Having 6 sessions like I was using some time ago is already messy with all the processes and stuff... add 10 more elements per session and its a nightmare. I'd rather have all layers visible at the layers panel.

**Comment by Luis-Fernando-Molina** [comment]
Only layer need to be open. 

![image](https://user-images.githubusercontent.com/9479367/69947030-188e3900-14ed-11ea-948b-3d27d09457bf.png)

**Comment by julian-molina** [comment]
Can you make it so that only the Layer Manager needs to be visible?

**Comment by Luis-Fernando-Molina** [comment]
all this was redone in the new release
