### ISSUE TITLE
Backtesting task does not work in Getting Started Guide, because of broken Trading System Reference

### ISSUE THREAD

**Issue by DanielHeckrath** [Superalgos/Superalgos#1133]
## Context

**Operating System:** Windows 10

**Software version:** today's master branch

**Workspace version:** default Workspace.json (Getting Started Guide)

**Reproducible:** the issue may be reproduced.

### 1. Explain what the problem seems to be.

I cannot run the backtesting portion of the getting started guide, because when I try to run the backtesting task, because it reports an error along the lines "Trading system reference needs to reference a trading system". The problem seems to be that the lightning strike trading system is not setup in the Getting Started Guide Workspace

### 2. Clearly explain what you wish to accomplish.

I wish to follow the Getting Started Guide from Start to finish

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

- Cloned my fork of the repository, on todays master branch
- Run the setup with `node setup`.
- Run superalgos with `node run`
- Follow getting started guide until node with id `70f84f2d-d298-4001-8696-467060ef51e9` (name Ready. Set. Go.)
- Start Lightning Strike Task
- Start Backtesting Task
- Backtesting Task shows an error

### 4. Explain what is the result you expect from your actions.

Expected result is that the backtesting is running using the references trading system

### 5. Explain what happens instead of the expected results.

Backtesting reports an error because the referenced trading system does not exist

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

Error on screen in the backtesting node that disappears after a few secconds. When starting superalgos I have several "Error on this branch" errors in the Testing Trading Tasks and Production Trading Tasks nodes, because of broken trading system references

**Comment by Luis-Fernando-Molina** [comment]
Thanks for reporting this, will take a look at it now.

**Comment by Luis-Fernando-Molina** [comment]
Hi, just posted a Fix at the master branch, can you please update the app with an 

app.update 

command at the search bar, restart, try again and report back if the fix did not solve the problem?
Thanks for reporting.

**Comment by DanielHeckrath** [comment]
Fix is working as expected. Backtesting works properly in getting started guide.

**Comment by Luis-Fernando-Molina** [comment]
Thanks for reporting back!
