### ISSUE TITLE
Save json files in a format that allows proper diffing in git history

### ISSUE THREAD

**Issue by DanielHeckrath** [Superalgos/Superalgos#1136]
**Is your feature request related to a problem? Please describe.**
As a developer I cannot properly comprehend the changes in the superalgos history, because many features are saved in optimized json format with stripped whitespaces.
This storage format eliminates many of the benefits we get from a normal commit history (eg line-by-line diffing).

**Describe the solution you'd like**
I would like a storage solution for plugins and other features that use json files, that allows proper diffing in the git history.
The easiest solution for this would be to pretty print the json output when saving it to disc, however this could be considered a performance regression, because it would consume more storage space compared to the current solution.

**Describe alternatives you've considered**
Another alternative would be to allow plugins to be stored in multiple files, that are merged together when loaded from disc. This solution would still have the problem that pretty printing json consumed slightly more space, but it would allow granular updates, and git diffing would most likely work because files are not to large to be diffed.
This solution would however be difficult to implement, because it would be unclear to me how to deterministically create those split json files from the current plugin files.

**Comment by Luis-Fernando-Molina** [comment]
Hi Daniel, you really made my day with this suggestion. We have been using this for displaying configs, but never crossed my mind to use it at saved files, and I was worrying me not be able to see the changes at json files at PRs. Now it looks so obvious. 

Already implemented for the backup and share features at the develop branch.

Keep those suggestions coming please!!!

**Comment by harrellbm** [comment]
Since plugins are primarily created in the design space using visual scripting.  It could also make sense to roll our own versioner similar to a git graph display.  That could also be turned into a debugger/diagnostics panel as well to make a unified workflow for creating and maintaining the supported plugins completely within the app.

**Comment by DanielHeckrath** [comment]
@Luis-Fernando-Molina thanks. One more thing I'd like to add, since I don't know exactly what you have already build on the development branch. Regarding file size, it might be worth considering to save the files in YAML instead of JSON, if you are pretty printing the JSON output.
I did a quick test with the Hello World Workspace:
Original Size: 2694kb
Pretty JSON (2 Spaces): 7025kb
YAML (2 Spaces): 5620kb

One feature that YAML has, that might also be interesting is better support for multi-line sttring. Eg given this property in the Hello World Workspace:
```
"config": "{ \n\"host\": \"localhost\", \n\"webPort\": \"34248\", \n\"webSocketsPort\": \"18041\"\n}",
```
The equivalent YAML representation would be:
```
config: |-
  { 
  "host": "localhost", 
  "webPort": "34248", 
  "webSocketsPort": "18041"
  }
```

Sample of the Hello World Workspace in YAML is available here: https://gist.github.com/DanielHeckrath/945c9a94f04af071ba0fa5aaa4d7a2ed

**Comment by Luis-Fernando-Molina** [comment]
I like it! would you take this task and do it yourself? I can help with directions.
