### ISSUE TITLE
Keyboard shortcut conflict

### ISSUE THREAD

**Issue by Kaffiend** [Superalgos/Superalgos#1235]
CTRL + SHIFT + A (reset aspect ratio) conflicts with chrome's shortcut to search tabs. Rather annoying. Suggestions for a new one? Seems like a good first contribution.

**Comment by Charlie67j** [comment]
Agreed. I switched to Brave to use this feature without issue to this point. If Chrome is the officially supported browser, this type of conflict will need to be resolved. I would personally prefer that anything Google or Apple related not be a prerequisite for the project.

**Comment by Luis-Fernando-Molina** [comment]
@Kaffiend feel free to look for a replacement that is not used and does not conflict with browser features, and PR the changes please.

Don't forget to change the Tutorial where it is mentioned and maybe some docs files.

You can find where it is mentioned by full searching the codebase, which includes docs and tutorials files.

**Comment by julian-molina** [comment]
> 
> 
> CTRL + SHIFT + A (reset aspect ratio) conflicts with chrome's shortcut to search tabs. Rather annoying. Suggestions for a new one? Seems like a good first contribution.

Actually, the correct keyboard shortcut is CTRL + SHIFT + ALT + A, which shouldn't conflict with Chrome's shortcuts. There was an error in one of the steps of the Welcome tutorial, and has been fixed.
