### ISSUE TITLE
Out of Memory when trying to sync a long period without data

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [Superalgos/Superalgos#126]
![image](https://user-images.githubusercontent.com/9479367/71827089-c027f980-309f-11ea-86bc-4e0240785752.png)

**Comment by bmcd77** [comment]
I've been testing superalgos and can confirm I've seen this error twice over the last 4 days. And yes it's when I'm running all bots which sync data with mininal initial DataStorage on a new setup.

**Comment by Luis-Fernando-Molina** [comment]
yes, something is wrong there while trying to sync up with the exchange after some days of not syncing. I will fix this directly on the next release, since there will be changes in that functionality once I implement the CCEX library for multi-exchange. The good thing is that if you restart the process it resumes from where it left and eventually the sync gets completed.

**Comment by Luis-Fernando-Molina** [comment]
this is fixed at the new release coming out very soon.
