### ISSUE TITLE
Installation error.

### ISSUE THREAD

**Issue by MYY-my** [Superalgos/Superalgos#1540]
It's not good that there was an installation error. Node version 12.18.4, package manager version 6.14.6
The error message pointed out problems installing the tensserflow.js library. The tenserflow.js documentation describes the requirements for windows 7 and higher, I have just this operating system. What else can you pay attention to, can tracing help?

**Comment by PLuv** [comment]
You are not the only user experiencing this issue.  I am looking into this issue now and will advise.
