### ISSUE TITLE
participation in the project

### ISSUE THREAD

**Issue by MYY-my** [Superalgos/Superalgos#1545]
How can I take part in this project?
My skils: react and ecosystem react (other librarys, state manager), html5, style-in-js, nodejs (basic), services cloud providers (aws, gcp, azure).

**Comment by Luis-Fernando-Molina** [comment]
You can contribute in any way you can / want. There are plenty of things to do and the doors are wide open. Any contribution can claim tokens at the distribution of the next release. Just start sending those PRs!

**Comment by harrellbm** [comment]
@MYY-my If you would like to get involved in the education project you can take a look at this project board:

https://github.com/orgs/Superalgos/projects/4

There is plenty to be done and even more room for ideas!

**Comment by MYY-my** [comment]
I would like to know if this service can be used as a console application,
instead of using it as a web service.

чт, 9 сент. 2021 г., 0:20 B Harrell ***@***.***>:

**Comment by harrellbm** [comment]
@MYY-my Superalgos is completely self hosted so you can definitely run it as a console application. The user interface is run by a browser but there is no need to access it from a network and can be run locally

**Comment by ssplatt** [comment]
The Issues area is not meant as a discussion forum. Please use the Forum, Telegram, or Discord to discuss further.
