### ISSUE TITLE
Backtesting Issue - B10 - Tutorial

### ISSUE THREAD

**Issue by fournarakis** [Superalgos/Superalgos#1650]
A big thank you for the effort of this community. 

Platform: **Windows 10**
Software: **Superalgos Beta10 Release**

After following the Tutorial steps of **Data Mining** and **Chart Navigation**, it was time for the **Backtest** process.
After clicking "Task > Run" and "Backtesting Session > Run", the following error appeared.
![image](https://user-images.githubusercontent.com/45131465/132047192-b8662e6c-d35d-4abf-a6a0-18823c998e5a.png)
The following lines appeared in the console Log:
![image](https://user-images.githubusercontent.com/45131465/132047443-14e2a59a-594f-404d-9830-6f03cffb23b9.png)

Has anyone experienced this issue? 
Did I performed anything in the wrong sequence?

**Comment by Luis-Fernando-Molina** [comment]
Hi, the reason you are seeing this message is because the strategy you are running, depends on the data of the Resistance and Support indicator, that it looks like you have not run yet. So the strategy can not run until the data of that indicator is available.

**Comment by ssplatt** [comment]
marking this as stale as the reporter has not updated the status in over a month. Please feel free to comment and reopen if your issue is not resolved.
