### ISSUE TITLE
Tutorial Expansions: New Tutorials Needed 

### ISSUE THREAD

**Issue by harrellbm** [Superalgos/Superalgos#1691]
List of needed tutorials:

- [ ] Further in depth Charting Tutorials

- [ ] Creating an indicator tutorial 

- [ ] Live trading Tutorial

- [ ] Api Map Tutorial 

- [ ] ML Tutorials 

-  [ ] Further in depth Governance Tutorials 

- [ ] how to set up docker container/cloud/daemonized  deployments tutorial 

- [ ] trading farm tutorial 

- [ ] Webhook tutorial 

- [ ] Paper trading/forward testing?

- [ ] Custom sensor bot

**Comment by MarkTradeink** [comment]
I want to take care of this when possible (following months)
