### ISSUE TITLE
Feature: Config Script 

### ISSUE THREAD

**Issue by harrellbm** [Superalgos/Superalgos#1702]
Config script to allow users to choose which projects they load out in an SA instance.

For example, if a user has a production instance of SA and wants it to be as trimmed down as possible, allow the removal of the education project leaving just the bare functional bones of the instance. This would give users greater control over the exact load out of an instance and facilitate more efficient trading farms and minimal deployments

**Comment by NAmorim** [comment]
Isn't this at the workspace level? Have some config flag to start a specific workspace?

**Comment by harrellbm** [comment]
Luis actually just implemented this.  If looks like this on the command line.  The basic idea was to be able to start different kinds of new users (non-tech, etc) at different workspaces on the first boot.  

You can test the feature out like this 
1. Key word 
2. Name of the workspace to load from the My-Workspaces folder.

![image](https://user-images.githubusercontent.com/55707292/138276200-23e32992-0e7c-4b31-8f8f-ac98a51687b0.jpeg)
