### ISSUE TITLE
Raw data sensor bot fails to retrieve new data at Midnight and goes into Fast Forward mode until restarted

### ISSUE THREAD

**Issue by ssplatt** [Superalgos/Superalgos#1724]
Some days at midnight the Fetch OHLCVs raw data sensor bot will fail to properly get new data from the exchange and will go into "Fast Forward" mode, where it is trying to get new data from the future (for example, one of my bots was in year 2166 this morning). This will cause the trading system to essentially halt for however long it takes the user to notice the issue and restart the Task. This effectively creates a network outage or power outage scenario in which a running live trading session will act on the old data as it is being processed and could make trades based off the old data instead of where the market is currently.

This was first noticed in Beta 10 and is still present in Beta 11.

This appears to be exchange independent as I have seen it happen with Binance US and Coinbase Pro.

**Comment by Smidy13** [comment]
Have just submitted a PR with a potential fix:
https://github.com/Superalgos/Superalgos/pull/1733

Haven't tested overnight yet, but I'll keep testing across all Exchanges.

If you can pull and trial it @ssplatt and let me know that'd be good.

**Comment by ssplatt** [comment]
I've been testing this for several days now. It does look like the issue with fast-forwarding into the future is gone so I think we can mark this as closed. However, I am seeing some other strangeness at the midnight date change so I'll explore that some more and open a new issue.

**Comment by ssplatt** [comment]
Of course right when I say that I find one last data mine I forgot to check before and it is in `fast-forward to next data`.

**Comment by ssplatt** [comment]
I haven't seen this happen in a few weeks so this may be resolved now. Marking closed until I have it happen again.
