### ISSUE TITLE
Feature: quick reference feature 

### ISSUE THREAD

**Issue by harrellbm** [Superalgos/Superalgos#1746]
Develop an alternative way to create references between nodes that does not require dragging node around.

Possibly built on top of node snap to location functionality

**Comment by Alphalama** [comment]
Drag and Drop on the workspace across multiple screens is sub optimal. One idea that I had was to implement a button for "add reference", once you push it, you can go to the node that needs to accept this reference and there will be a button "accept reference". If you push it, reference is etablished. Once that it is the case those 2 elements connected cannot refer to anything else, until reference is removed.

**Comment by harrellbm** [comment]
This is a great Idea! If you would like some help implementing this there are plenty of people willing to help on the telegram and discord channels

**Comment by julian-molina** [comment]
Would be nice if we conserve the visual effect with the rings highlighting which nodes may accept the reference.

**Comment by Alphalama** [comment]
> Would be nice if we conserve the visual effect with the rings highlighting which nodes may accept the reference.

Absolutely, that is a very nice feature and also the reference connections / grey lines. I think the linking how it works now should remain intact, just add a new linking possibility in addition to existing functionality. 

Unfortunately I am not a developer, so can’t help on that end but I can test and give feedback.

**Comment by Alphalama** [comment]
> This is a great Idea! If you would like some help implementing this there are plenty of people willing to help on the telegram and discord channels


Unfortunately I am not a developer, so can’t help on that end but I can test and give feedback.

**Comment by NAmorim** [comment]
Implemented
