### ISSUE TITLE
Issue: Bug report has two invalid links to documentation

### ISSUE THREAD

**Issue by jance1499** [Superalgos/Superalgos#1789]
## Context

*Complete and adjust the contents, leaving the information that fits your case and deleting the information that doesn't.*

**Operating System:** macOS `Big Sur 11.6`

**Software version:** `Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (arm64)`

**Reproducible:** the issue may be reproduced.

### 1. Explain what the problem seems to be.

The links in the bug report template are not valid.

### 2. Explain, step by step, what you've done to achieve the goal. The team will follow these steps to reproduce the issue, so be precise.

1. Create a new issue
2. Select Bug Report
3. Click on the links

They are provided here for convenience.

[Troubleshooting Guide](https://docs.superalgos.org/suite-how-to-troubleshoot-an-issue.html)
[How to report an Issue](https://docs.superalgos.org/suite-how-to-report-an-issue.html)

### 3. Explain what is the result you expect from your actions.

I expected to be directed to documentation.

### 4. Explain what happens instead of the expected results.
I actually was directed to the root of the Superalgos website.  `https://superalgos.org/`

**Comment by SingingDwarf** [comment]
Not possible to fix this currently, as there is no online documentation.
