### ISSUE TITLE
Feature:  Hosted Superalgos Demo 

### ISSUE THREAD

**Issue by harrellbm** [Superalgos/Superalgos#1865]
Create a startup switch the place the Superalgos platform into demo mode.  This would allow an instance of Superalgos to be hosted to allow people to try out Superalgos completing the first few tutorial and able to look through the docs.

the demo mode would need to do the following:

- accept multiple UI clients so many people can try the demo at once 
- Have data for the demo preprocessed 
- Disable all tasks and client side “heavy lifting” to avoid clashes between the various UIs running at the same time

**Comment by Luis-Fernando-Molina** [comment]
I would allow only task ran from localhost ws connections.  In this way, logged in locally the opeartor of the hosted client can start data mining but no other UI will be alble to stop it or start any other task.

**Comment by ssplatt** [comment]
aws fargate and digitalocean options deployed.
