### ISSUE TITLE
Oscilator's scale change while panning the chart

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#199]
Oscillators have an independent rate scale all of the default chart. However, when the chart is panned to the left or right, the oscillator scale changes. The problem occurs with all settings of automatic/manual rate scale for the oscillator.

This video shows the issue.

![Superalgos video capture (9)](https://user-images.githubusercontent.com/13994516/79200088-36be5b00-7e36-11ea-8f05-8d90d5897f4b.gif)

**Comment by Luis-Fernando-Molina** [comment]
fixed
