### ISSUE TITLE
Implement javascript code edito

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [Superalgos/Superalgos#203]
https://github.com/ajaxorg/ace/

**Comment by unfernandito** [comment]
Hi Luis, i wanna contribute in this project.

Can you indicate me which file has the responsibility of this?

Thanks

**Comment by Luis-Fernando-Molina** [comment]
Hey! yes, sure. This is the file:

![image](https://user-images.githubusercontent.com/9479367/83346026-64456200-a319-11ea-898b-a2e3f2cc8ab4.png)

Let me know if you need anything else.

**Comment by NAmorim** [comment]
Implemented
