### ISSUE TITLE
Script to clone complete infrastructure required to fork trading systems

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#204]
Users may want to clone an existing trading system to produce optimizations. However, using the clone feature leaves them a long way from actually being able to test the clone and browse simulations on the charts.

A script is required to:

1. Create a backtesting session in the development environment.
2. Set up session based data references.
3. Create a time machine that includes a timeline chart for the corresponding backtesting session.

I think that this script should not produce all sorts of sessions with all sorts of timeline charts... that would create too many things. I believe that the fine-tuning workflow may involve keeping multiple versions of the same trading system to compare ideas at each stage, that would at some point be deleted, and only the best one would remain.

Once the user has finished the backtesting optimization, then he/she will want to create the remaining sessions for the select trading system. That should be done with a different action.

**Comment by Luis-Fernando-Molina** [comment]
A lot of infrastructure was created to facilitate. Not exactly what you asked for but in this direction. By adding missing sessions on the Data Storage or Missing Time Machines at the Charting System this process was greatly simplified.
