### ISSUE TITLE
Test Social Bot  

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#209]
When adding a Social Bot would be useful to have a Test Bot function to make sure everything is set up correctly and running
![image](https://user-images.githubusercontent.com/38046064/79953277-e1a8c780-847b-11ea-9945-9077f39fdabe.png)

**Comment by Luis-Fernando-Molina** [comment]
Good one! thanks!

**Comment by Smidy13** [comment]
Have submitted a commit with this functionality for the Telegram Bot. 
Commit: https://github.com/Superalgos/Superalgos/pull/838/commits/17d21c501d03bf72ad574a2f768d17b1f4b1acb0

**Comment by Luis-Fernando-Molina** [comment]
@9808us now you can ask @Smidy13 anything you want....! :-)
