### ISSUE TITLE
SMA and EMA not displaying all values in chart when value is less than 2 decimals

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#214]
![image](https://user-images.githubusercontent.com/38046064/80474994-8168c880-8948-11ea-8bfe-afaab81289e8.png)

When operating on markets that have a price expressed with many decimals, for example RVN / BTC with RVN = 0.00000375, then Popular SMA/EMA do not show the full correct values ​​in the relative panel in chart. See screenshot

**Comment by Luis-Fernando-Molina** [comment]
https://github.com/Superalgos/Superalgos/issues/215

**Comment by Luis-Fernando-Molina** [comment]
Fixed at develop branc
