### ISSUE TITLE
Edit code / config should close when you click outside it

### ISSUE THREAD

**Issue by Eduardo678-dotcom** [Superalgos/Superalgos#221]
Currently, when one edits the code inside a node, be it a condition in a strategy, a procedure loop, procedure condition, etc., the editor closes spontaneously when the mouse pointer moves away from the frame of the editor, which makes editing work a bit cumbersome. It is proposed that the editor be closed by left-clicking outside the editing frame.

**Comment by NAmorim** [comment]
Implemented with new editor. PR #2600
