### ISSUE TITLE
"Social Bot" should announce that the "Live Trading Session" has been stopped.

### ISSUE THREAD

**Issue by EduRemix** [Superalgos/Superalgos#222]
When a "Live Trading Session" is turned on, the "Social Bot" announces the event. But if active sessions are stopped through the "Live Trading Task" or the "Live Trading Task Manager", the "Social Bot" does not announce that the session has stopped. The "Social Bot" should announce that the "Live Trading Session" has been stopped, if the event happens through the "Live Trading Task" or the "Live Trading Task Manager".

**Comment by Luis-Fernando-Molina** [comment]
You are right.

**Comment by Luis-Fernando-Molina** [comment]
This was implemented in Beta 6
