### ISSUE TITLE
Problem dragging chart

### ISSUE THREAD

**Issue by EduRemix** [Superalgos/Superalgos#223]
When the candlestick chart is dragged by clicking with the left mouse button, the chart moves erratically.

**Comment by Luis-Fernando-Molina** [comment]
can you please post a video to see what you see?

**Comment by EduRemix** [comment]
With the left button pressed, as soon as I touch the mouse to drag the graph in any direction, the chart always jumps suddenly to the right.
NOTE: I am using a mac with touchpad.

[Screen Recording 1.mov.zip](https://github.com/Superalgos/Superalgos/files/4644535/Screen.Recording.1.mov.zip)

**Comment by Luis-Fernando-Molina** [comment]
Ok this is a bug, very annoying and difficult to find. Remember you can use your keyboard while it is fixed.

**Comment by Luis-Fernando-Molina** [comment]
This seems to be fixed, reopen if not.
