### ISSUE TITLE
Setting arbitrary start date in Time Range generate errors

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#225]
If start date in Time Range under Backtesting is set for a candle that doesn't exist, then an error is generated, see screenshot

![image](https://user-images.githubusercontent.com/38046064/81744892-1ec51000-94a4-11ea-8cdd-798c8852f30b.png)

Maybe would be better to just start from the first available candle

**Comment by Luis-Fernando-Molina** [comment]
This is not an error but a kind of warning. We assume that if you do not have some dependency, the task needs to wait until it is generated. Sometimes this might happen naturally if for example you data mine in a machine different than where you run backtests. If the data mining machine stops for any reason, all the others needing their data should wait and not crash. That is the intention here. Your proposal assumes a very simple use case where you are firing up one backtest and you dont care when it starts. The overall idea here is to prepare the system for more complex use cases where you might have a lot of pre-defined backtests to run against a strategy that you or a team of people is working on. If the backtests arbitrary starts wherever they find the data that can get messy very quickly and difficult to plan large scale setups.

I can see a way to define a special date at the Time Range, like 'Begining of Marlet' for the ones that do not care to find out which is the begining of the dataset.
