### ISSUE TITLE
SL/TP do the math wrong when dealing with ALTS

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#230]
Superalgos has bad behaviour when dealing with alts tokens (shitcoins) with value of few sats

This creates problems with TP/SL and the whole strategy (as well with some indicators)

![image](https://user-images.githubusercontent.com/38046064/81910966-ebca6b80-95cc-11ea-8382-573c21172360.png)

It is proposed to check if a 8 digits decimals are needed to solve the problem

**Comment by Luis-Fernando-Molina** [comment]
Fixed at the develop branch:

![image](https://user-images.githubusercontent.com/9479367/82236622-a4c5d880-9934-11ea-9186-3a1306601c83.png)
