### ISSUE TITLE
Some differences between Superalgos and Exchange candles

### ISSUE THREAD

**Issue by Eduardo678-dotcom** [Superalgos/Superalgos#231]
I found this situation, there is a big difference in some candles bodies between Bitfinex chart and Superalgos chart. The market is PNK/ETH, it is a very low volume market. Anyway, I think the candles should always be the same.
If I find more, I'll update the data.

![Superalgos PNK-ETH](https://user-images.githubusercontent.com/54202149/82070752-7bf3d800-96d5-11ea-9560-b3b26c803d43.jpg)
![Bitfinex PNK-ETH](https://user-images.githubusercontent.com/54202149/82070777-857d4000-96d5-11ea-83b8-859df69f75ff.png)

**Comment by EduRemix** [comment]
Another case, but in an importante market: BTC/USDT - 24hs - Bitfinex - 2-4-2019. It seems that Superalgos takes the closing price of the previous candle to make the opening price of the current candle, but in this way it eliminates the gaps.

![Bitfinex BTC-USDT](https://user-images.githubusercontent.com/54202149/82081245-42779880-96e6-11ea-8fc9-b1759d71d430.jpg)
![Superalgos BTC-USDT](https://user-images.githubusercontent.com/54202149/82081256-499ea680-96e6-11ea-8164-4e603de6cfa3.jpg)

**Comment by Luis-Fernando-Molina** [comment]
What I have seen is that the data provided by exchanges is no perfect. Sometimes the exchange is not sending 1 candle (when asking them all 1 min candles)  or sending candles with a timestamp that does no start at an exact minute. So I am not 100% surprised to see this now. Having said that,  that does not mean there could be some bug in Superalgos. Please continue posting examples and some day we will check them all.
