### ISSUE TITLE
Single paragraph on labels of Simulation Plotter

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#232]
Labels showing ROI and TP or Stop exit may sometimes become entangled with other labels referring to the name of the strategy or the name of the situation:

![image](https://user-images.githubusercontent.com/13994516/82460416-6a397880-9ab9-11ea-8ac9-087e0fb83249.png)

If all labels were on the same paragraph, the overall experience would improve and information would be easier to  find.

If possible, I would suggest the following format:

**ROI: 2.05%**
(Take Profit)
Strategy Name
Situation

**Comment by Luis-Fernando-Molina** [comment]
These labels where moved to panels at Beta6
