### ISSUE TITLE
Agregar Information al Panel de resultados del Testing

### ISSUE THREAD

**Issue by bartulin** [Superalgos/Superalgos#233]
Seria bueno tener en el panel de información de los resultados del testeo , los parámetros iniciales que fueron configurados: fecha de inicio, fecha de fin y balance inicial para darle contexto a la información del resultado de dicho test.

![image](https://user-images.githubusercontent.com/64693149/82491494-17f95700-9abb-11ea-8a4e-5bd25caef9a8.png)

**Comment by Luis-Fernando-Molina** [comment]
Esto va a ser posible en la version Beta 6.

**Comment by Luis-Fernando-Molina** [comment]
This is done:

![image](https://user-images.githubusercontent.com/9479367/94014961-8c673e00-fdac-11ea-986f-72f25f6c571c.png)
