### ISSUE TITLE
Some errors in announcements

### ISSUE THREAD

**Issue by EduRemix** [Superalgos/Superalgos#234]
I have configured the announcements in my trading strategy and since my bot made the Take Position, two things have happened to improve:
1) The announcements appear in the wrong order (See attached print screen).
![Mike bot](https://user-images.githubusercontent.com/54202149/82724735-941cb600-9cd8-11ea-913b-ad75bb6bbca7.png)
The logical order should be as follows:
-Trigger Stage
-Trigger On
-Take Position
-Open Stage

2) The announcements are sent multiple times again at the close of each 24-hour candle while the trade is open (see attached print screen). In the image you see 2 a.m. by offsetting my time zone.
![Mike bot repeat](https://user-images.githubusercontent.com/54202149/82724740-9da61e00-9cd8-11ea-98ab-39ce72ad70a6.png)

**Comment by Luis-Fernando-Molina** [comment]
Plese re open if this still happens in beta6, where the trading engine was completely re written
