### ISSUE TITLE
Initial Date Time for Paper Trading

### ISSUE THREAD

**Issue by EduRemix** [Superalgos/Superalgos#238]
Sometimes it is necessary to do a "Paper Trading", but starting with a date before the current one, since you may want to simulate the live evolution of a trade that has been open from a date before the current one.
It would behave similarly to a hybrid between Backtesting and Paper Trading.

**Comment by Luis-Fernando-Molina** [comment]
This would be a new mode, since paper trading is understood as from now on in general.

**Comment by EduRemix** [comment]
Yes, it is true that it is a new way, but to simplify it I thought that putting a start date for paper trading would be enough. At least it served to capture the idea, I think it is very interesting in case you want to see the evolution of a trade that has opened a few candles before the current test date.

**Comment by Luis-Fernando-Molina** [comment]
For Paper trading, Fordward and Live in beta6 if you do not specify at the session parameters an initial datetime, then it starts from current time. If you specify one in the past, it will go through the candles like in a backtest but executing the orders at the exchange.
