### ISSUE TITLE
Snapshot error reporting for 15min SMA 200

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#244]
Look at the screenshot

![image](https://user-images.githubusercontent.com/38046064/83282840-78cf1080-a1da-11ea-87bb-5b5556a096e4.png)

Value for 15-min-popularSMA-sma200/chart is fixed at 1 while value for 15-min-popularSMA-sma200/chart is corrected reported

**Comment by Luis-Fernando-Molina** [comment]
This might get fixed at Beta 6, where the trading engine is completely re-written.

**Comment by Luis-Fernando-Molina** [comment]
Please reopen if you find it not working on beta6
