### ISSUE TITLE
Binance: Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#245]
A live trading session produced the simulation correctly but orders did not reach the order book.

![image](https://user-images.githubusercontent.com/13994516/83349483-7af9b200-a335-11ea-9f81-ed3b051d5b82.png)

I found the following error in the logs:

```
['2020-05-30T20:12:51.555Z',3134,'Exchange API','[INFO] createOrder -> Entering function.']
['2020-05-30T20:12:51.555Z',3135,'Exchange API','[INFO] createOrder -> market = undefined_undefined']
['2020-05-30T20:12:51.555Z',3136,'Exchange API','[INFO] createOrder -> side = sell']
['2020-05-30T20:12:51.555Z',3137,'Exchange API','[INFO] createOrder -> cost = 18.940041']
['2020-05-30T20:12:51.555Z',3138,'Exchange API','[INFO] createOrder -> amount = 0.002']
['2020-05-30T20:12:51.555Z',3139,'Exchange API','[INFO] createOrder -> price = 9470.0205']

['2020-05-30T20:12:53.206Z',3140,'Exchange API','[ERROR] createOrder -> err = "InvalidNonce: binance {\"code\":-1021,\"msg\":\"Timestamp for this request was 1000ms ahead of the server's time.\"}\n    at binance.throwExactlyMatchedException (C:\\Superalgos-master\\TaskServer\\node_modules\\ccxt\\js\\base\\Exchange.js:543:19)\n    at binance.handleErrors (C:\\Superalgos-master\\TaskServer\\node_modules\\ccxt\\js\\binance.js:2015:26)\n    at C:\\Superalgos-master\\TaskServer\\node_modules\\ccxt\\js\\base\\Exchange.js:639:18\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async timeout (C:\\Superalgos-master\\TaskServer\\node_modules\\ccxt\\js\\base\\functions\\time.js:178:24)\n    at async binance.request (C:\\Superalgos-master\\TaskServer\\node_modules\\ccxt\\js\\binance.js:2026:26)\n    at async binance.createOrder (C:\\Superalgos-master\\TaskServer\\node_modules\\ccxt\\js\\binance.js:1245:26)\n    at async Object.createOrder (C:\\Superalgos-master\\TaskServer\\ExchangeAPI.js:140:25)"']

['2020-05-30T20:12:53.231Z',3141,'Trading Simulation -> Live Trading WHB','[INFO] runSimulation -> loop -> putOpeningOrder -> onOrderCreated -> Entering function.']
['2020-05-30T20:12:53.231Z',3142,'Trading Simulation -> Live Trading WHB','[INFO] runSimulation -> loop -> putOpeningOrder -> onOrderCreated -> DEFAULT_FAIL_RESPONSE ']
['2020-05-30T20:12:53.231Z',3143,'Trading Simulation -> Live Trading WHB','[ERROR] runSimulation -> loop -> putOpeningOrder -> onOrderCreated -> Message = Operation Failed']
['2020-05-30T20:12:53.232Z',3144,'Trading Simulation -> Live Trading WHB','[INFO] runSimulation -> afterLoop -> Entering function.']
['2020-05-30T20:12:53.232Z',3145,'Trading Simulation -> Live Trading WHB','[INFO] runSimulation -> callback -> recordsArray.length = 0']
```

Full log: [Loop.00000004.0000.txt](https://github.com/Superalgos/Superalgos/files/4707445/Loop.00000004.0000.txt)

**Comment by julian-molina** [comment]
As per the suggestions in this [CCXT Issue](https://github.com/ccxt/ccxt/issues/850), it is important to synchronize the time in your local machine to this specific server (on a Windows 8.1 system):

![image](https://user-images.githubusercontent.com/13994516/83358417-aac7aa80-a373-11ea-9344-816dbae62202.png)

Synchronizing once may not be enough. Binance recommends having the system self-synchronize every ten minutes, however, in my OS that seems to be not possible.

I did adjust the synchronize the time manually.

After testing several transactions, at least one of them did not go through, and was rejected with the same error.

Igor Kroitor [made a suggestion](https://github.com/ccxt/ccxt/issues/850#issuecomment-361112005) to do this upon instantiation:

```
import ccxt
b = ccxt.binance({ 'options': { 'adjustForTimeDifference': True }})
```
And commented "It will adjust for the clock unsynchronization itself, but this is less secure."

On a subsequent post [he explained what he meant about that being less secure](https://github.com/ccxt/ccxt/issues/850#issuecomment-382787816).

**Comment by Luis-Fernando-Molina** [comment]
>  'adjustForTimeDifference': True 

This was implemented. Let me know if you have this issue again.
