### ISSUE TITLE
Custom Parameters in Trading Session 

### ISSUE THREAD

**Issue by rico4dev** [Superalgos/Superalgos#246]
Possibility to define Custom Parameters in Trading Session.
Custom Parameters can be accessed by Trading System (Read/Write)

**Benefit**
Increased flexibility of Trading System

- Use Custom Parameters in Conditions to take decisions based on Trading Session
_For example use different Parameters in ETH/USD & BTC/UDS Trading Session_
- Store Values in Custom Parameters
_Like Global Variables for Trading System in a running Trading Session_

![custom_parameters](https://user-images.githubusercontent.com/66202445/83349813-efcdeb80-a337-11ea-91df-219c8224c705.png)

**Comment by Luis-Fernando-Molina** [comment]
This is a very good idea, and I will implement it on Beta 6 currently under development.

**Comment by Luis-Fernando-Molina** [comment]
Added today to Beta 6:

![image](https://user-images.githubusercontent.com/9479367/84244086-6d95b200-ab03-11ea-9b61-6a7d7fa253e1.png)

**Comment by Luis-Fernando-Molina** [comment]
Closing this because beta6 is already at beta6.
