### ISSUE TITLE
Calculate Indicators dynamically (On the fly)

### ISSUE THREAD

**Issue by rico4dev** [Superalgos/Superalgos#247]
For some simple Indicators (like Rate of Change) often many different Periods/Parameters are needed for Backtesting (to find profitable Setting) or in Trading Session to handle different Assets

Possibility to calculate Indicator on the fly in a Trading Session. 
Maybe store result in a Custom Parameter to avoid ongoing calculations

**Comment by Luis-Fernando-Molina** [comment]
This is a great idea! I am already implementing it at Beta 6

![image](https://user-images.githubusercontent.com/9479367/84247133-eeef4380-ab07-11ea-9982-f3a1b2922007.png)
