### ISSUE TITLE
Education Project - LAN Network Node appears as Network Node at the Docs

### ISSUE THREAD

**Issue by MarinitaMarina** [Superalgos/Superalgos#2509]
![image](https://user-images.githubusercontent.com/88245524/140412437-0b271030-26d4-44c8-8efb-75607955fa76.png)

For example:

![image](https://user-images.githubusercontent.com/88245524/140412833-6466563f-8e34-44a6-aac8-18d726fdd22d.png)

This happens at many places.

**Comment by whtv** [comment]
We should find more appropriate names for the `LAN Network` and `LAN Network Node` nodes. I understand the choice in light of the current state of connection security, but there is no inherent limitation to LAN. Maybe `Trading Farm` or `Client Network` and `Client Node` respectively?
