### ISSUE TITLE
Improve EMA panel by adding color to the relative EMA text

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#252]
To improve the readability of the EMA panel (but can also be extended to other panels) you could write the text of the relative EMA with the color used for the plot

![image](https://user-images.githubusercontent.com/38046064/83625956-0cb32a80-a595-11ea-97f2-3086cd60d812.png)

**Comment by Luis-Fernando-Molina** [comment]
Good Idea.

**Comment by Luis-Fernando-Molina** [comment]
This was solved.
![image](https://user-images.githubusercontent.com/9479367/94586840-06526800-0282-11eb-9fd6-c2601c4bfd42.png)
