### ISSUE TITLE
Indicator Bots: synchronization problem between frontend and backend

### ISSUE THREAD

**Issue by anvd** [Superalgos/Superalgos#255]
Install and launch the backend on one computer running Ubuntu 18.04. Access the frontend from another computer running MacOS (with SSH tunnel).
The sensor bots run on the backend side. However, the corresponding icons on the frontend side are not updated correspondingly. The data are generated correctly on the backend side.
Please check the attached image.
<img width="1440" alt="Screen Shot 2020-06-05 at 9 38 53 PM" src="https://user-images.githubusercontent.com/12640348/83897045-3f207b80-a77f-11ea-8459-48b52fe625e0.png">

**Comment by Luis-Fernando-Molina** [comment]
This should be solved, in beta 6.
