### ISSUE TITLE
Telegram Announcements adding an ID# to keep track

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#259]
Regarding the integration with Telegram, in many groups (trading) they use Cornix or in any case automatic trading functions based on Telegram messages. A typical example of how one of these messages is structured is this:

Trade ID: # 6.03
🛑 SHORT (TRADE)

Position Size: 10%
Leverage: 10x

ENTRY ZONE: 9705-9790

Target 1- 9662
Target 2 - 9612
Target 3 - 9557
Target 4 - 9512
Target 5 - 9379
Target 6 - 9228
Target 7 - 8957

STOP LOSS: 9860

Risk: 8/10

Then the trade get uptaded (posting new messages) when conditions/targets are met but using the same #Trade ID

This makes possible to customers of Telegram channels to implement auto-trading by simply following the channel

It will allow a more sophisticated commercial setup for who want to broadcast signals business 

I think that giving Risk or splitting signals at different targets should be left to the user that implement the trading system.

What is important is to be able to give the trade an unique ID# and being able to track it, and to properly format the message

**Comment by Luis-Fernando-Molina** [comment]
You will be able to do this is Superalgos Beta 6 currently under development, since you will have access to all variables the Trading Engine uses from Formulas. We just need to add one more variable, positionId.

Does the Id needs to be a number or can it be a string with numbers and letters?

**Comment by 9808us** [comment]
> Does the Id needs to be a number or can it be a string with numbers and letters?

It can be with numbers and letters, just it should be unique (and short) to better identify the trade

**Comment by Luis-Fernando-Molina** [comment]
As promised, here is your id:

![image](https://user-images.githubusercontent.com/9479367/94006766-9daa4d80-fda0-11ea-949b-b707cafc0a69.png)
