### ISSUE TITLE
Move on-screen error messages below the node

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#260]
**Is your feature request related to a problem? Please describe.**
I have noticed that users, including developers, are not noticing the text of error messages shown on-screen, maybe because it falls out of smaller screens, as it is rendered outside of the (expanding) red ring.

**Describe the solution you'd like**
I think that moving the error message right below the affected node, in a fixed position (not affected by the animation of the red ring) would make it perfectly visible.

**Comment by Luis-Fernando-Molina** [comment]
I tried but It didnt work well.
