### ISSUE TITLE
Save logs at the level of each run of the trading session

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#264]
**Is your feature request related to a problem? Please describe.**
When investigating an issue with a particular run of a backtest (see issue #263) I found that the logs were overwritten by subsequent backtests, so I lost the logs of the first test simply by running another test. 

**Describe the solution you'd like**
When running a trading session it is desirable that each run of the session would generate independent logs.

**Describe alternatives you've considered**
N/A

**Additional context**
At the moment, it seems like logs are kept for each run of the trading task. There is a folder with the session ID, and then subfolders with  execution date. But the execution date seems to be the date of the execution of the trading task, no the trading session. Therefore, all backtests run within the same run of the task will overwrite the logs.

**Comment by Luis-Fernando-Molina** [comment]
That behavior is by desing. If you want to have a log for each run, just restart the task. Usually people would not want to accumulate such a big amount of logs files, so for the specific situation where you do want to keep all the logs, just restart the task.
