### ISSUE TITLE
Precision of the markers of the take position candle in the simulation graphics

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#265]
**Is your feature request related to a problem? Please describe.**

The way in which simulations are drawn over the charts seem to misrepresent the moment in which the position is taken. I noticed users being confused about this.

The capture below shows a trade with the current candle marked in yellow. The current candle is the one being evaluated to take the position. That is, the position is taken at the moment that candle closes.

![image](https://user-images.githubusercontent.com/13994516/84498453-f867df80-acb0-11ea-9b0f-e2f94755f102.png)

However, the triangle representing the trade originates at the ```begin``` of the take position candle, a moment in which the position was not open. Also, the periods counter considers this the first period, when the position was not yet open.

The same goes for the Stop target, and the TP target as well. They both show for the candle in which the position was not open yet.

**Describe the solution you'd like**

I think it may be OK that the strategy is marked as triggering / taking the position at that candle, but maybe the Strategy layer marker is enough. Or maybe even this is wrong.

The rest of the markers in the simulation and trades layer should shift to the ```end``` of the period, and it's the next period that should count as period 1.

**Describe alternatives you've considered**

Maybe there should be a specific indication of which is the candle that was evaluated to take the position, but I think that is only a particular case, as a strategy may be looking into different time frames to take a position. 

**Additional context**

The trade in the image is a WHB backtest run at the 1H time frame, with no slippage for clarity.

**Comment by Luis-Fernando-Molina** [comment]
All these plotters were re-written in beta6. Please switch to this new version and report any problem you find there.
