### ISSUE TITLE
Candles Volumes cannot rename .tmp file

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#267]
## Before you open an issue

There are two requirements to open an issue:

1. You must first follow the [Troubleshooting Guide](https://docs.superalgos.org/suite-how-to-troubleshoot-an-issue.html)

2. If your issue hasn't been resolved by following the Troubleshooting Guide, then follow the guide on [How to Report an Issue](https://docs.superalgos.org/suite-how-to-report-an-issue.html).

## Context

*Complete and adjust the contents leaving the information that fits your case and deleting the information that doesn't.*

**Operating System:** Windows 8.1

**Software version:** today's develop branch 

**Workspace version:** Binance - WHB - BBTB.json | My custom workspace 

**Reproducible:** the issue may not be reproduced.

### 1. Explain what the problem seems to be.

The symptom is similar to what we've seen before when Candles Volumes stops with an error and leaves one of the market files with a .tmp extension.

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

This is the main error:

Error renaming temp file -> err = Error: EPERM: operation not permitted

## Attach relevant log files and error screenshots

[Loop.00000011.0000.json.zip](https://github.com/Superalgos/Superalgos/files/4781626/Loop.00000011.0000.json.zip)

**Comment by julian-molina** [comment]
The same error happened again, this time on the Simple Workspace. These are the full logs of the run:
[D.2020.06.29.T.17.28.43.zip](https://github.com/Superalgos/Superalgos/files/4847352/D.2020.06.29.T.17.28.43.zip)

**Comment by ssplatt** [comment]
This has been open for over a year. Is it still an issue?
