### ISSUE TITLE
Paper Backtest Label Run even if it's already running

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#268]
**Operating System:** Windows 10

**Software version:** today's develop branch 

**Workspace version:** My custom workspace 

**Reproducible:** the issue may be reproduced.

### 1. Explain what the problem seems to be.

Set up a Trading Farm
Set Testing Environment on a different PC (cloud)
Run a Paper backtest
Close browser
Launch Superalgos again
Paper backtest has a RUN label even if it's already running

![image](https://user-images.githubusercontent.com/38046064/84736348-e8e4e100-afa5-11ea-931a-5433ccff5ad2.png)

**Comment by ssplatt** [comment]
This has been open for over a year. Is it still an issue?
