### ISSUE TITLE
Ghost trades on Paper Backtest

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#271]
**Operating System:** Ubuntu 18.04 VM on Azure

**Software version:** develop branch 15/06/2020

**Workspace version:** My custom workspace 

**Reproducible:** the issue may not be reproduced.

## Explain your issue

See these 2 screenshot taken on 1min TF. At exactly 0:00 20/06/2020 2 ghost trades are counted

![image](https://user-images.githubusercontent.com/38046064/85289548-ec8dd180-b497-11ea-9f45-351a39694c1c.png)

![image](https://user-images.githubusercontent.com/38046064/85289609-00d1ce80-b498-11ea-80b3-d5c7bcbbd491.png)

I received 2 telegram announcements too at that time!

### 1. Explain what the problem seems to be.

Error in reporting the never done trades

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

I attach logs but it seems that some days are just not present n the log (But not sure about that as it's first time I look at logs)

## Attach relevant log files and error screenshots

[Logs.zip](https://github.com/Superalgos/Superalgos/files/4813284/Logs.zip)

## Attach you custom workspace if any

Attach custom workspace here.

**Comment by 9808us** [comment]
Another logs from a new fresh Paper backtest, same problem. Exactly at 0:00 it is counted a "ghost" trade
[Logs2.zip](https://github.com/Superalgos/Superalgos/files/4835266/Logs2.zip)

WebM video
https://1drv.ms/u/s!AtQPXYDAMiS_hKxOPs1ikaP46xOUQQ

**Comment by Luis-Fernando-Molina** [comment]
Since this issue is from beta5 version and we are almost at beta6, where the trading engine was completely rewritten, I close this issuue.
