### ISSUE TITLE
Improve info panels with additional data

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#272]
**Is your feature request related to a problem? Please describe.**
No

**Additional context**
Is it possible to add more infos about current simulation set up?
Maybe adding Start-End Time?

![image](https://user-images.githubusercontent.com/38046064/85869794-7c02ef80-b7cc-11ea-8890-731cdefeac5b.png)

**Comment by Luis-Fernando-Molina** [comment]
Done in the latest version of beta6, you will find it at the Episode Panel.

![image](https://user-images.githubusercontent.com/9479367/93979706-f87e7d80-fd7d-11ea-8776-fb875db9e31e.png)
