### ISSUE TITLE
Copy node path does not work at User Defined Variable at the develop branch

### ISSUE THREAD

**Issue by Raplh2502** [Superalgos/Superalgos#2731]
The copy node path menu does not work at the User Defined Variable node. When I click on the item, nothing happen. All the USV nodes have the same behavior. 
![image](https://user-images.githubusercontent.com/82839817/143306409-d49a6ca9-698e-47cf-9bd4-2aa3bba126d8.png)

**Comment by cozed-gh** [comment]
Sent a fix for this one. Should be alright by tomorrow.

**Comment by cozed-gh** [comment]
Fix is merged at develop.
@Luis-Fernando-Molina How does one close this issue? :)
