### ISSUE TITLE
Beta6 Auto-Rename tasks that are linked to a strategy

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#274]
**Is your feature request related to a problem? Please describe.**
No

![image](https://user-images.githubusercontent.com/38046064/89558005-f5522100-d813-11ea-87fb-d3d901382c60.png)

Consider adding the ability to "auto-name" linked tasks like it is for a Session Reference that take it's name from the reference it's linked

So if we link a trading system, then all the "tree" tasks could be auto-renamed with the name of the trading system

**Comment by Luis-Fernando-Molina** [comment]
When you install a market in the latest version of beta6 in develop you get the task named as the session.

![image](https://user-images.githubusercontent.com/9479367/93975415-b7836a80-fd77-11ea-8c1d-0858f348947f.png)
