### ISSUE TITLE
Beta 6: Irresponsive trading task after waking from sleep mode

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#275]
## Context

*Complete and adjust the contents leaving the information that fits your case and deleting the information that doesn't.*

**Operating System:** Windows

**Software version:** today's develop branch 

**Workspace version:** official testing workspace

**Reproducible:** the issue may

### 1. Explain what the problem seems to be.

When a trading task (in the testing or production environments) are left running and the machine is put to sleep, upon waking up, the session under the task may NOT be run. Instead, the task needs to be stopped and restarted before the session may be run.

### 2. Clearly explain what you wish to accomplish.

I want to be able to run a task when coming back from sleep mode without needing to restart the task.

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

1. Run a trading task.

2. Put the PC in sleep mode.

3. Wake the PC Up.

4. Try to run the trading session under the task. You will get an error.

### 4. Explain what is the result you expect from your actions.

The session should run.

### 5. Explain what happens instead of the expected results.

Despite the fact that the visual interface shows the task is running, the session thinks it's not.

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

On-screen error: Session needs a Process Instance parent to be running.

**Comment by ssplatt** [comment]
This has been open for over a year. Is it still an issue?
