### ISSUE TITLE
Error ENOENT during node initialization

### ISSUE THREAD

**Issue by reverendo7zero** [Superalgos/Superalgos#305]
I'm experiencing this error after the node starts:

########################################
...
You are running Superalgos Beta 7

What's new? The following was implemented here:

Multi-Project Infrastructure ....... This allow us to integrate crypto projects into Superalgos. Note that with this upgrade you will need to download and calculate market data again.

What's next? At the development pipeline we have:

Ethereum Integration ............... This will allow mining data from an Ethereum network node, create indicators with it, an use it on strategies.
Machine Learning Infrastructure .... This will enable a new kind of Bot that can learn from data mined. Later that knowledge can be used at trading strategies.

[ERROR] Client -> client-> uncaughtException -> err.message = spawn xdg-open ENOENT
[ERROR] Client -> client-> uncaughtException -> err.stack = Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

########################################

Test system:
Raspberry pi 3, standard Raspberry OS distro, light version.

Thank you.

**Comment by julian-molina** [comment]
Make sure you are using the ```minMemo``` option to run Superalgos, like this:

```node run minMemo```

If you wish the RPI to run the backend only, so that you access the frontend from a different machine, then add ```noBrowser``` too:

```node run noBrowser minMemo```

Let us know if this solves your issue.

**Comment by reverendo7zero** [comment]
Hello Julian,
solved, thank you.
I use the minMemo as stated in the docs, but still I had the issue: adding noBrowser solved it !

Many thanks :)

Lodovico Pesenti

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
