### ISSUE TITLE
Could we calculate dollar or volume bars from current price time bars? 

### ISSUE THREAD

**Issue by davidwynter** [Superalgos/Superalgos#306]
My preference is to build indicators on top of volume bars or dollar value bars. Is SuperAlgo flexible enough for me to take the price bars and convert them to dollar values bars (e.g. $500 change, either up or down forms a new bar) or volumes bar (e.g. 50 instruments up or down forms a new bar)

The ability to take each price bar and determine if it forms a new bar up or down. If not enough dollar value to volume value occurs in that bar save the value for use in the calculations for the next bar, where it's value is added to that new bar and the test is repeated. This method is repeated until a new bar is formed. Any residual from the delta is stored to be added to the following bar.

The calcs for these as defined in Python are included here [Medium article](https://towardsdatascience.com/financial-machine-learning-part-0-bars-745897d4e4ba)

Renko bars are a proxy for dollar value bars.

**Comment by julian-molina** [comment]
The short answer is yes, the data mining hierarchy provides the tools to build such indicators with great flexibility. 

1. Take a look at the [data mines section](https://docs.superalgos.org/suite-data-mines.html) of the docs.

2. There's also a series of [video tutorials](https://docs.superalgos.org/suite-how-to-build-an-indicator.html) explaining how to build indicators.

3. The Masters data mine features the Volume Analysis indicators. Check it out for reference. It is not documented, but it's available in the data mine for everyone to use.

**Comment by davidwynter** [comment]
Thank you
