### ISSUE TITLE
Chart Rate Scale not showing correctly

### ISSUE THREAD

**Issue by CarnivalBen** [Superalgos/Superalgos#314]
The rate scale on the charts does not always show correctly.

For example, on Binance trading pair AVAX/USDT at around 7am on 4th Jan (UTC), the scale shows as all 3.00, instead of dividing between the integer numbers on the scale.

![image](https://user-images.githubusercontent.com/3448911/103522431-47a27700-4e72-11eb-9a88-5a8d2202070c.png)

If I scroll up slightly on the vertical scale, it jumps to 4.00, so it looks like its just rounding to the nearest int.

![image](https://user-images.githubusercontent.com/3448911/103522603-87695e80-4e72-11eb-9a8c-f5a803635da7.png)

Not quite sure how to find the version of the software, workspace, etc... I'll try to find and update the issue. It does say "Superalgos Beta 8" in the bar at the top if that helps :)

**Comment by Luis-Fernando-Molina** [comment]
Thanks for the pull request. Merged.
