### ISSUE TITLE
Make the profiles easily searchable in the governance project

### ISSUE THREAD

**Issue by slow-crypto** [Superalgos/Superalgos#3160]
Building my profile i started referrimg mentors and influencers. There are actually 81 and I suppose we are getting more every week. I found it hard to find the corrosponding persons, as they were nor sorted in any way.

I would like to have them in an alphabetical order.

Regarding my monitorsize (15") and the fact that we have more contributors very soon, I wouldnt know, how to access the profiles, as my screen is already full of Profile pictures.
Zooming in doesnt help, either. 
So a searchform that links to the corrospondent node would be the best way to find the needed profiles.

**Comment by harrellbm** [comment]
This feature is actually already available.  If you open the docs tab and search a user name.  The User Profile will appear in the search results.

If you click on it (when not in map mode) it will take you directly to that users profile.

This needs documented more so will shift this issue to a documentation issue

**Comment by slow-crypto** [comment]
thanks @harrellbm, so I will close this issue here?

**Comment by slow-crypto** [comment]
Wait, @harrellbm . I have looked up and clicked on it, but wont get to the profile. What is meant by map mode?

<img width="858" alt="Bildschirmfoto 2022-01-08 um 00 41 11" src="https://user-images.githubusercontent.com/82347142/148620748-dc012adc-d5f2-48c5-ab1c-aaeee18953d5.png">

**Comment by slow-crypto** [comment]
After playing around I found out what you meant by not using the map mode. It is any other mode than showing all the profiles in a map.
Thanks again!

**Comment by harrellbm** [comment]
@slow-crypto map mode us when you right click to zoom out on the whole workspace.  If you left click to zoom in and then click on the user profile it should work
