### ISSUE TITLE
"White" and "Dark" sections of the UI is hard on the eyes

### ISSUE THREAD

**Issue by isysd-mirror** [Superalgos/Superalgos#3165]
## Context

**Operating System:** all

**Software version:** today's master branch

**Workspace version:** default Workspace.json (Getting Started Guide)

**Reproducible:** the issue may be reproduced.

### 1. Explain what the problem seems to be.

The division of the UI into a "White Room" and a "Dark Room" is poor UX because it messes with contrast and eye focus.

### 2. Clearly explain what you wish to accomplish.

The UI should pick a single (configurable, if possible) theme, which is either light, or dark. Going between light and dark shocks the eyes.

**Comment by isysd-mirror** [comment]
I've been told this is configurable in some deep area... Going to try that, and close this if it works. Definitely this process would be good for an FAQ, because many people like me have preferences for dark or light.

**Comment by wonder6oy** [comment]
Did you find a solution for this?  It's very hard on my eyes as well.

**Comment by harrellbm** [comment]
Solved by #4304
