### ISSUE TITLE
Live-trading behavior hitting stops and take profit targets

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#32]
Currently, when a take profit or stop target are hit while live trading, the app waits until the candle closes to place the closing order at the exchange.

This is not the desired behavior, because it creates an inherent risk for stops to become totally unpredictable. In trading, the first and foremost rule is to preserve capital. The only way we can guarantee capital will be preserved is to place the order immediately after the stop target is hit. This is the desired behavior for take profit as well. We should not wait until the candle closes.

**Comment by Luis-Fernando-Molina** [comment]
The current Trading Bot for Low Frequency Trading does not consider open candles as part of its computation. If you need to have the STOPs and TP very often, reduce the time frame in which your live trading session runs up to a minimum of 1 minute.
