### ISSUE TITLE
AppImage doesn't start on linux due to NSS cert error

### ISSUE THREAD

**Issue by isysd-mirror** [Superalgos/Superalgos#3211]
## Context

*Complete and adjust the contents leaving the information that fits your case and deleting the information that doesn't.*

**Operating System:** Linux (Xubuntu x64 20.04)

**Software version:** today's develop branch, Dec 20 nightly, Dec 22 nightly

**Reproducible:** the issue may? be reproduced.

### 1. Explain what the problem seems to be.

I have tried running the AppImage on linux in various ways, and it never fully loads the app. The window opens, but the canvas either remains white or stuck on "The UI is loading..."

I have tried building the AppImage locally and running different nightly builds. In all cases, when the AppImage is run from command line, an error like this is thrown:

```
$ ~/Downloads/Superalgos-1.0.1-20211222.AppImage
Checking for update
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[800605:1222/093633.030066:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[800561:1222/093633.435757:ERROR:nss_util.cc(286)] After loading Root Certs, loaded==false: NSS error code: -8018
Update for version 1.0.1-20211222 is not available (latest version: 1.0.1-20211222, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```

After discussing with @NAmorim, it seems like there's an issue with a check for new releases on github.com. This fits with the error message, which seems to relate to x509 certificate databases (NSS). Presumably the electron client needs to be provided with an NSS database which includes the root key which signed the x509 cert for github.com.

### 2. Clearly explain what you wish to accomplish.

Start the electron app on linux. Specifically, I wish to use the User Profile builder.

**Comment by isysd-mirror** [comment]
On further research, it seems node also maintains an NSS database... Perhaps that is where we should be looking. See:

https://github.com/nodejs/node/pull/35546

**Comment by isysd-mirror** [comment]
More debugging indicates that this isn't the reason the app won't load. Catching the error, and also simply commenting out the `autoUpdater.checkForUpdatesAndNotify()` line still result in the same hung loading screen. Perhaps there are two issues here.

**Comment by isysd-mirror** [comment]
@NAmorim I'm stumped on this, could you please take a look? I'm going to use the web app to begin my work on multiple-blockchain support for the SA token. Not urgent, I think.

**Comment by NAmorim** [comment]
Did some tests but on my Ubuntu LTS it did work. 
Reading about this in the AppImage issue list, this might be related to not having the latest versions of nss. 
So my first try would be "sudo apt install nss3"

**Comment by isysd-mirror** [comment]
@NAmorim I already had the latest libnss3 version. Really stumped on this one. :/
