### ISSUE TITLE
Plugins (especially User Profiles) should not be stored in this repo (use submodule)

### ISSUE THREAD

**Issue by isysd-mirror** [Superalgos/Superalgos#3223]
### 1. Explain what the problem seems to be.

This repository is growing, and in some areas is already creating bottlenecks. I think the most obvious case, as a frequent governance workspace user, is the user profiles and corresponding github profiles. Furthermore, as an observer of this repository, I see that a large percentage of the PRs are actually user registrations, or updates. This presents a noise and performance issue, particularly as an order of magnitude more users register.

### 2. Clearly explain what you wish to accomplish.

The simplest way to resolve this issue is to move the user profiles (and perhaps generically all plugins) into a git submodule, or other tracked, hashed, sub-folder. This would create a distinct storage area, and message / PR channel for each plugin space. Since these belong to users, not to developers, it makes sense to segregate the data and messages.

**Comment by PLuv** [comment]
👍

**Comment by Luis-Fernando-Molina** [comment]
Agree, this is yet another pending stuff to be solved. The solution should involve al plugins of all projects. Please explain how it would end up, and how it would work.

**Comment by isysd-mirror** [comment]
The way I see it, for public plugins, there are two organizational options. Considering this impacts project / team workflow, I think it is best to consider carefully.

## Single Plugin Submodule

We create a new top-level directory under Projects called Plugins. This one directory is a new repository, linked as a submodule. All plugins are organized within, mirroring the directory naming structure in Projects.

This option would be good if all user plugins basically behave the same, and involve the same parties.

## Submodule per Plugin

This is the easiest, and most flexible option, but creates significantly more repositories to manage. It maintains the exact current directory structure, which is a bonus. Also the the individual repositories give further separation to plugins, in case they involve different moderators, users, or rules.

**Comment by isysd-mirror** [comment]
One consideration for creating more repositories is that users would need to fork those, as well. If this is automated, no problem. There are reasons for it, technically. But it could get tedious, or annoying.

On the weight of it, I'm inclined toward thinking that individual repos would be good future proofing, in addition to being the fastest to implement...

**Comment by isysd-mirror** [comment]
After chatting, we decided to go with the individual repos model. I'll review the code around it more closely, and estimate the effort involved. If it is as small as I imagine, I'll have a candidate to review in a few days.

**Comment by PLuv** [comment]
I think only few or none will be providing plugins that do not know how to use git.  So no need to consider the difficulty involved.  Also, plugins are not touched as often (besides the user-profile ones of course). 👍

**Comment by Luis-Fernando-Molina** [comment]
Please automate the forking and cloning for those installing the platform and running it from code. We should not add more stuff to do, and all should be handled in the background as much as possible.

**Comment by isysd-mirror** [comment]
I created a PR for this, and I think it is pretty safe to run. The only issue is upgrading, since we need to create and fork the repo quickly, and the commands are strict. See my note on PR #3266.

**Comment by isysd-mirror** [comment]
Create new PR #3659 and believe it is ready to merge. There is a superficial conflict reported by the bot, but @PLuv and I already manually resolved it, and it is sa
