### ISSUE TITLE
Documentation: Colons prevent the recognition of Docs pages to form tooltips

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#3228]
When the page name in the Docs is succeeded by colons [:], the phrase is not recognized and the tooltip is not formed. See image below for clarity.

![image](https://user-images.githubusercontent.com/13994516/147286067-51fa67b1-4fa9-4dfa-9250-44c352f3df5e.png)

**Comment by julian-molina** [comment]
The same happens with the quotation mark:

![image](https://user-images.githubusercontent.com/13994516/147287461-560d6664-51e0-4d12-bd53-4464228c5e82.png)

**Comment by BastianMuc** [comment]
PR for fix submitted.

**Comment by harrellbm** [comment]
@BastianMuc Did this PR get merged already?

**Comment by BastianMuc** [comment]
@harrellbm Yes, merged on develop.
