### ISSUE TITLE
Install-a-New-Market-Tutorial crashes UI while loading

### ISSUE THREAD

**Issue by BastianMuc** [Superalgos/Superalgos#3248]
## Context

**Operating System:** MacOs 12.0.1, Chrome 96.0.4664.110

**Software version:** today's master branch

**Workspace version:**
Plugin Workspace Install-a-New-Market-Tutorial
community-workspaces-012-install-a-new-market-tutorial-plugin-workspace.json

**Reproducible:** the issue may be reproduced.

## Explain your issue

When opening the tutorial "Install-a-New-Market" via Workspaces, the UI gets stuck while loading the Workspace in status:**
**Rebuilding the Charting Space...**

This status can only be overcome by reloading the UI.

### 2. Clearly explain what you wish to accomplish.

Tutorial Workspace should fully load without crashing the UI.

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

- Launch Superalgos
- Close Welcome Tutorial
- Click on Workspaces
- Select "Install-a-New-Market-Tutorial" Plugin Workspace

### 4. Explain what is the result you expect from your actions.

Install-a-New-Market-Tutorial fully loads.

### 5. Explain what happens instead of the expected results.

- Getting-Stated-Tutorial-Workspace is fully unloaded
- Install-a-New-Market-Tutorial-Workspace is partially loaded
- Loading process stops in Status "Rebuilding the Charting Space..."

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

Non on-screen errors
Browser Console reports "Paused before potential out-of-memory crash", relating to EditorPage.js, Line 338

**Comment by 9808us** [comment]
Have you tried to run node setup and check if anything change?

**Comment by BastianMuc** [comment]
> Have you tried to run node setup and check if anything change?
node setup did not cause any change.

I can also reproduce the issue on a second, separate installation (MacOS packaged).

**Comment by NAmorim** [comment]
Master has been updated. Can you still reproduce?

**Comment by BastianMuc** [comment]
Retested with current master, issue no longer persists. Closing.
