### ISSUE TITLE
infinite loop in httpInterface mergePullRequests

### ISSUE THREAD

**Issue by isysd-mirror** [Superalgos/Superalgos#3263]
The `mergePullRequests` case handler creates a `setInterval` loop which never ends. Implement some sort of finite iteration instead...

**Comment by NAmorim** [comment]
Appears to be legacy code as user profiles are now automatically validated and merged.

@Luis-Fernando-Molina can this "gov.prs" command be deleted?

**Comment by isysd-mirror** [comment]
Related to this, and also #3541, it seems like there's a lot of dead code lying around. Perhaps we can do a review one day with any parties who might be able to help identify such deprecated functions to be archived?
