### ISSUE TITLE
Signature error when contributing my profile

### ISSUE THREAD

**Issue by slow-crypto** [Superalgos/Superalgos#3267]
hello, i need help with this error, i have problems with the signature hash.
https://github.com/Superalgos/Superalgos/pull/3265

**Comment by slow-crypto** [comment]
i am running superalgos on a mac big sur, i had created two api keys on github,  which may cause the problem.
Is it possible to delete this fork and start all over again with a new pull request and with a new api key (the others deleted)?

**Comment by aririvas** [comment]
Hi!, github APIs are independent of the forks you have in your account, I understand that you can use them with differents fork simultaneously

**Comment by slow-crypto** [comment]
Well I didnt really understand what you mean. at first I just want to upload only fork, which iis my user profile.
I have created the two, because with the first one it wasnt working. Then I created another one, which I wouldnt do with the knowledge I have now.
When looking at the both generated Aps from github only the first was used, the other one not.
To repeat my question again:
Will I have issues deleting the fork and start with a new contribution of my profile?

**Comment by aririvas** [comment]
No issues, you can delete your fork and start over again.. But always make sure before you make a contribute, to fetch the upstream to minimize the differences (new changes and updates) with the main fork of SA. In your github account, go to your fork and make click on Fetch Upstream

**Comment by slow-crypto** [comment]
OK I will try that. THANKS!

**Comment by aririvas** [comment]
your welcome! I couldn't find your user on Telegrams groups, you can ask things like this here https://t.me/superalgosnontechusers

**Comment by slow-crypto** [comment]
I am the second martin from Germany, maybe i am "martin Pie " in Telegram? I dont know.
I just had a zoom call with gustavo and we didnt get further than this.

**Comment by slow-crypto** [comment]
II have created a new profile using the seed phrase. and it can be found here:
https://github.com/Superalgos/Superalgos/pull/3274

**Comment by slow-crypto** [comment]
Finally, the profile was submitted
