### ISSUE TITLE
Trading System incorrectly reports an error in a condition javascript when functions are used in a certain way

### ISSUE THREAD

**Issue by CarnivalBen** [Superalgos/Superalgos#329]
Branch: develop (2021-01-07)

If a condition within a Trading System is set to the following javascript code:

```
const func = (candle) => candle.close;
func(chart.at05min.candle) > 1;
```

The backtest will run successfully, but an error will be marked on the chart and highlighted on the condition node, even though the javascript was valid and did not error:

![image](https://user-images.githubusercontent.com/3448911/103892564-b5090e80-50e3-11eb-9259-c27872453716.png)

This is related to the code that creates the snapshot within `addCodeToSnapshot(nodeWithCode) { ... }` in `snapshot.js`. It doesn't correctly parse the javascript to pull out the chart object identifiers.

The problem occurs whenever a `chart.xxx` object is used as the first argument in a function.

As a workaround, you can add a space before and after each chart identifier, as shown here marked with `<space>`:

```
const func = (candle) => candle.close;
func(<space>chart.at05min.candle<space>) > 1;
```

**Comment by CarnivalBen** [comment]
@Luis-Fernando-Molina I'm just trying to thinking of a way to fix this, but I'm not sure how to do it.

The code in `addCodeToSnapshot()` as it is today tries to find all the `chart.<timeframe>.<product>.[previous.]<property>` identifiers, and evaluate them.

But in my example above, you can see I'm passing the `chart.at05min.candle` object into the function, and then reading the `.close` property of the object passed into the function.

If the user is free to write whatever javascript they want in the condition, then it would be impossible to parse the code to find all the `chart.whatever` properties that were used.

A couple of other ways people could write it are:

```
// read using an indexer
const prop = "close";
const example = chart.at05min.candle[prop];

// read properties by iteration
let sum = 0;
for (const k of Object.keys(chart)) {
    sum += chart[k].candle.open;
}
```

I don't see how its possible to parse the code to find every possible way someone could write ways to get the chart data.

What are the `strategyKeys` and `positionKeys` used for?

**Comment by Luis-Fernando-Molina** [comment]
I have to check that code because to be honest I don't remember anything about it. Will come back here once I do.
