### ISSUE TITLE
Previous chart objects are not present on the first timeframe of the day when timeframes less than an hour are used

### ISSUE THREAD

**Issue by CarnivalBen** [Superalgos/Superalgos#330]
Branch: develop (2021-01-08)

The `previous` reference is missing in the chart objects for the first timeframe of the day when a timeframe below 1 hour is used.

For example:
```
chart.at05min.candle.previous
```
is `undefined` when used in a condition or formula at 2021-01-08 00:00:00.

Some console logging added to one of the conditions in the trading system shows this:

![image](https://user-images.githubusercontent.com/3448911/103998240-c27dd180-5193-11eb-9511-629da1a4acdc.png)

This has the effect of causing glitches in trade system processing:

![image](https://user-images.githubusercontent.com/3448911/103998601-11c40200-5194-11eb-8f6a-88a170640689.png)

**Comment by Luis-Fernando-Molina** [comment]
I've just pushed a fix to develop. Haven't test it myself. Please check if that fixes this bug and if so, please close the issue.
