### ISSUE TITLE
Link description with translation appears in the original english language 

### ISSUE THREAD

**Issue by mARTin-B78** [Superalgos/Superalgos#3306]
File: 
Superalgos\Projects\Governance\Schemas\Docs-Tutorials\C\Creating\Creating-Your-User-Profile-Tutorial\
creating-your-user-profile-tutorial-022-tutorial-step-github-glory.json

I have translated the Link on that page into German but the translation does not appear.
By Looking at the Json file I see the Translation there - but it does not show up in the docs as German.
![creating-your-user-profile-tutorial-022-tutorial-step-github-glory json](https://user-images.githubusercontent.com/91568406/147789827-76c73a68-ae65-46cd-a93f-eaa18a921208.png)

**Comment by BastianMuc** [comment]
PR #3553 is fixing this.
