### ISSUE TITLE
Tutorial "Chapter VIII - Testing a Trading Idea - The Trigger Stage" Step "34. Tutorial Step - Let's Do This..."

### ISSUE THREAD

**Issue by mARTin-B78** [Superalgos/Superalgos#3308]
Issue on the Page "35. Tutorial Step - Let's See What We've Got!" in the "Chapter VIII - Testing a Trading Idea - The Trigger Stage"

"Let's See What We**AMPERSAND**ve Got!"
It shows "AMPERSAND" instead of the apostrophe in the title.

Not sure if the content of that page is right too.

![35  Tutorial Step - Let's See What We've Got!](https://user-images.githubusercontent.com/91568406/147791484-08fb10df-3a18-4f42-bfeb-7c972f7f0674.PNG)

Same at Step
37. Tutorial Step - Can't See What's Expected?
![37  Tutorial Step - Can't See What's Expected](https://user-images.githubusercontent.com/91568406/147791586-e4ce281e-4865-4e74-9929-9a7c33802d75.PNG)

**Comment by BastianMuc** [comment]
Issue occurs when there's more than one Apostrophe (') in a Doc headline, as the navigateTo-function in the docs space only replaces the 1st one.

Function changed to replaceAll, submitted PR #3353.
