### ISSUE TITLE
Governance: Alternative controls on token power flows

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#3500]
When driving token power flows, we can only control the flow by using a `percentage` parameter that determines the percentage of power in the parent node that will flow to the child node.

Two additional control mechanisms are desirable:

* `absolutePower` would be used to define a fixed amount of token power, instead of a percentage.

* In the case of Contribution Claim nodes `percentageReward` would be used to define the amount of power equivalent to a certain percentage of the rewards available in the referenced node. That would make internal distributions within teams a lot easier.

**Comment by BastianMuc** [comment]
Resolved via #4824 and #4825.
The parameter name for absolute power allocations is `amount` .
Percentages of a rewards pool can now be claimed via `claimedShare` .
