### ISSUE TITLE
Governance: Include new Biswap and 1Inch LPs in Liquidity Program.

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#3614]
The Liquidity Program in the governance project currently verifies LP tokens in various LPs on PancakeSwap. 

We have recently set up a new liquidity pool on Biswap, another DEX on the BSC. This is a transaction adding liquidity to the pool:

https://bscscan.com/tx/0x9afa534332b861f37ac2b236aa0353e8857a2bbd0c62db451a14be9a65e055fe

We need the Liquidity Programs to account for LP tokens in the new pools to incentivize adding liquidity on Biswap too.

This is important as it is part of the requirement to get CMC to verify the market cap and circulating supply for the token.

We will need to do the same for other exchanges, so you may want to consider that.

**Comment by julian-molina** [comment]
New LP on 1Inch needs to be included in governance too.

This is a Deposit transaction in the BTCB-SA LP:

https://bscscan.com/tx/0x9d309097a1bd10d164391752155ac2e9b2861cbfd367f125c3353757c8f7c812

And this is a Withdraw TRX:

https://bscscan.com/tx/0x89aca219c24321fa85e086bd44e7e7d51e6f2491c27e51c964a4c867781ae4b2

**Comment by BastianMuc** [comment]
I'm beginning to look into this.

**Comment by BastianMuc** [comment]
Changes committed. Pools BNB (Biswap) and BTCB (1inch) should now be included to the counted liquidity.

As it seems, both exchanges currently do not hold pools for the other supported assets (ETH, BUSD). The setup is now flexibilized, so that additional pools can be added quickly
