### ISSUE TITLE
'Install a New Market' tutorial step leads to "Page Not Found" in documentation window

### ISSUE THREAD

**Issue by BrandonBaylis** [Superalgos/Superalgos#363]
## Context

*Complete and adjust the contents leaving the information that fits your case and deleting the information that doesn't.*

**Operating System:** Chrome browser GUI accessed on Windows 10, backend running on Raspberry Pi OS

**Software version:** Superalgos Beta 7

**Workspace version:** default Workspace.json (Install a New Market Tutorial)

**Reproducible:** Easily reproduced

### 1. Explain what the problem seems to be.

When going through the "Install a New Market" tutorial, on the "Set Up the Market" section when you get to Step 2: Reference Base A. it opens the right-side panel to assumedly display a help page about establishing references but it leads to a "Page Not Found".

### 2. Clearly explain what you wish to accomplish.

I'm not sure whether this page is still under development or whether it's simply a bad URL.  Some context would be helpful if it is under-development.

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

1. Open "Install a New Market" tutorial.
2. Proceed through steps up until "Set Up the Market" section.
3. Continue to Step 2: Reference Base A.
4. Right-side panel appears with "Page Not Found"

### 4. Explain what is the result you expect from your actions.

I would expect the correct page reference to appear, otherwise a "Page under development" to show it's still being worked on.

### 5. Explain what happens instead of the expected results.

"Page Not Found" error appears.

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

The generic "Page Not Found" error has appeared in the documentation window.

## Attach relevant log files and error screenshots

Screenshot of the error message: https://i.imgur.com/NC5BYgY.jpg

**Comment by Luis-Fernando-Molina** [comment]
Thanks for reporting this. We are finishing Beta 8, in which the main change was to bring the external docs website, inside the app. This means that all the content was migrated and this bug should not be there anymore. I will close the issue hoping this will be the case, so as to clean up the issues queue. Feel free to re-open it if you see it again in beta 8 once released.
