### ISSUE TITLE
Downloading releases asks foror username and password at some point after downloading nearly 210mbs each time. which doesnt seem to be the same as github's

### ISSUE THREAD

**Issue by daves254** [Superalgos/Superalgos#3710]
## Before you open an issue

There are two requirements to open an issue:

1. You must first follow the Troubleshooting Guide in the built-in Docs.

2. If your issue hasn't been resolved by following the Troubleshooting Guide, then follow the guide on How to Report an Issue, also in the Docs.

## Context

*Complete and adjust the contents leaving the information that fits your case and deleting the information that doesn't.*

**Operating System:** Windows | MacOs | Linux | Other (include the version on either case)

**Software version:** today's master branch | today's develop branch 

**Workspace version:** default Workspace.json (Getting Started Guide) | Simple Workspace.json | Workspace - Binance - WHB - BBTB.json | My custom workspace 

**Reproducible:** the issue may | may not be reproduced.

### 1. Explain what the problem seems to be.

Type your explanation here.

### 2. Clearly explain what you wish to accomplish.

Type your explanation here.

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

Type your explanation here.

### 4. Explain what is the result you expect from your actions.

Type your explanation here.

### 5. Explain what happens instead of the expected results.

Type your explanation here.

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

Type your explanation here.

## Attach a video reproducing the issue

Attach video here.

## Attach relevant log files and error screenshots

Attach logs here.

## Attach you custom workspace if any

Attach custom workspace here.

**Comment by BastianMuc** [comment]
Hi @daves254 - I'm sorry, but I do not fully understand this issue.
Can you please provide more details according to the reporting template on when this issue occurs and how it can be reproduced? Thank you!

**Comment by julian-molina** [comment]
Not enough info on what the issue is about.
