### ISSUE TITLE
Governance: Improvement on the list of Pools

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#3771]
The POOLS list in the Governance system is a bit hard to read. Usually, the user may want to see the ranking of pools as clearly as possible, but the pool name is "hidden" after a long path of nodes, which makes reading the actual name of the pool harder than it needs to be. See the image below.

Take this record as an example:

Superalgos - Governance Programs - Incentives for Providing Liquidity to SA Markets - Liquidity Program - Liquidity Rewards BTCB

I propose the name of the pool should be first, and in bold, and then the path to the head of the hierarchy should go to the left, and between parenthesis:

**Liquidity Rewards BTCB** (Superalgos - Governance Programs - Incentives for Providing Liquidity to SA Markets - Liquidity Program)

![image](https://user-images.githubusercontent.com/13994516/152525994-985fee22-6ce0-4b1b-91fe-e98a16f7f294.png)

**Comment by devosonder** [comment]
fixed
