### ISSUE TITLE
Refactor Plugin Workspaces for Template Workspaces

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [Superalgos/Superalgos#382]
Stop calling Plugin Workspaces and replace those for Template workspaces, because they do not behave like all the other plugins, and that is confusing.

**Comment by julian-molina** [comment]
I wouldn't call them template workspaces, as most don't fit that description. We've got, for instance, workspaces whose main purpose is to feature tutorials. Maybe sample workspaces is more appropriate. This is also fitting for those featuring Trading Systems, which are samples.

**Comment by MarkTradeink** [comment]
Hello I have a PR ready for this. I replaced all "Plugin Workspace" by "Sample Workspace".

PR: #4863 

New issue: #4864

**Comment by MarkTradeink** [comment]
I haven't changed the following as this may be used for all plugins... Would be nice if you can confirm

```
PROJECT_PLUGIN_MAP
PATH_TO_PLUGINS
```
![image](https://user-images.githubusercontent.com/82445653/235787979-f2e535a9-bc3f-4ab0-9f07-b0650cc5bf94.png)

**Comment by harrellbm** [comment]
> I haven't changed the following as this may be used for all plugins... Would be nice if you can confirm
> 
> 
> 
> ```
> 
> PROJECT_PLUGIN_MAP
> 
> PATH_TO_PLUGINS
> 
> ```
> 
> ![image](https://user-images.githubusercontent.com/82445653/235787979-f2e535a9-bc3f-4ab0-9f07-b0650cc5bf94.png)
> 
> 

Yup these should stay!
