### ISSUE TITLE
node setupPlugins does not set upstream correctly

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#3972]
## Context

**Operating System:** Same bug on Windows and Rasp Pi4. Can't check other OS

**Software version:** Not applying

**Workspace version:** Not applying 

**Reproducible:** the issue may be reproduced.

## Explain your issue

node setupPlugins do not set the upstream correctly if repos are already forked.

See screenshots below to have a better understanding, I screenshotted all the relevant passages:

- Fresh install

![image](https://user-images.githubusercontent.com/38046064/160593907-35e8d1ff-5899-409f-a6c8-805ece8f059d.png)

- node setup + node setupPlugins

![image](https://user-images.githubusercontent.com/38046064/160593973-cbedd632-e325-4fea-8690-eb617b5ce803.png)

As it's clearly visible no upstream is set up

This issue gives then an error in console when using SA and the Contribution tab
 
![image](https://user-images.githubusercontent.com/38046064/160593391-81464745-90ed-4a9a-a339-fd58ea2a7b73.png)

**Comment by devosonder** [comment]
When the "node setup" command was executed, the upstream address of the Superalgos project was set.

**Comment by theblockchainarborist** [comment]
This was resolved with PR #4156, Correct?
