### ISSUE TITLE
cannot update

### ISSUE THREAD

**Issue by BigJonMMXX** [Superalgos/Superalgos#3979]
windows10, git, github, githubDesktop, node.js...

So i followed the instructions - forked SA, cloned SA...
Spent *days* getting to grips with all the above to get SA working...
Spent *days* going through tutorials - loving what i saw - until it was time to actually start...
found a video about using SA (ridiculously bad, by a person who clearly has *never* made instructions before) and they use a new version of SA... 
so updates:--------------------------------
node.js        ---just install newer release ontop (this also updates python3 and VScode Tools)
git               ---open cmd>git update-git-for-windows
gitdesktop, VScode, chrome ---done through software (eg: help->about->update)

But update Superalgos ??? How ???
sorry, i just cant find the answer. everyone talks about pulling, pushing, merging local code with *my* online repository ?!?!?! 
Can someone please tell me how i can get the latest version of SA without losing my stuff ???

**Comment by BigJonMMXX** [comment]
Update software ------------------------------------------------------------------------------------------------
node.js ----------- just install newer release ontop (this also updates python3 and VScode Tools)
git ----------------- open cmd>git update-git-for-windows
gitdesktop, VScode, chrome -------- done through software (eg: help->about->update)
SA ----------------- goto your copy of SA on github (github.com/UserName/Superalgos,
-----------------------& in the middle of the screen click “fetch upstream”)
Rclick c:\GitRepos\Superalgos → git bash here
----------------------$ node setup

**Comment by 9808us** [comment]
Come in our support chat in Telegram, we can help with this issues.

https://t.me/superalgoscommunity

SA develop branch is constantly adding new features and now for example you can easily update your SA install with the Contribution tab


![image](https://user-images.githubusercontent.com/38046064/161004942-c124345d-5396-4364-8cf6-81cb58e5a75b.png)

**Comment by BigJonMMXX** [comment]
Thank you.

**Comment by BigJonMMXX** [comment]
So i gave it a go: contributions -> update...
"something went wrong. check the console"

[INFO] Downloading from https://github.com/Superalgos/Superalgos
[INFO] Your local repository Superalgos was already up-to-date.
[INFO] Downloading from https://github.com/Superalgos/Governance-Plugins
[INFO] Your local repository Governance-Plugins was successfully updated.
[INFO] Downloading from https://github.com/Superalgos/Foundations-Plugins
[INFO] Your local repository Foundations-Plugins was already up-to-date.
[INFO] Downloading from https://github.com/Superalgos/Algorithmic-Trading-Plugins
[ERROR] Error updating master
Error: Auto-merging Trading-Mines/Masters.json
CONFLICT (content): Merge conflict in Trading-Mines/Masters.json
Automatic merge failed; fix conflicts and then commit the result.
From https://github.com/Superalgos/Algorithmic-Trading-Plugins
 * branch            master     -> FETCH_HEAD

    at Object.action (D:\TecProjects\GitRepos\Superalgos\node_modules\simple-git\dist\cjs\index.js:1194:25)
    at PluginStore.exec (D:\TecProjects\GitRepos\Superalgos\node_modules\simple-git\dist\cjs\index.js:1229:29)
    at D:\TecProjects\GitRepos\Superalgos\node_modules\simple-git\dist\cjs\index.js:1589:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (D:\TecProjects\GitRepos\Superalgos\node_modules\simple-git\dist\cjs\index.js:1587:16)
    at GitExecutorChain.<anonymous> (D:\TecProjects\GitRepos\Superalgos\node_modules\simple-git\dist\cjs\index.js:1571:44)
    at Generator.next (<anonymous>)
    at fulfilled (D:\TecProjects\GitRepos\Superalgos\node_modules\simple-git\dist\cjs\index.js:55:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

(so far, all i've done is go through tutorials)

**Comment by 9808us** [comment]
You have modified something and the download encountered an error.

You are on Windows 10, right?
Ok so SA (SuperAlgos) have different options to test/use it, in the README file you can read about this.

For me the fastest way is to just clone the repository from github.

Mandatory and to be done just the first time:

- node + git installations 
- Github account -> After creating the account go to your User Settings - Developer Settings and generate a Personal Access Token. Give it a name, select No Expiration and tick gist, repo, workflow, write:discussion. Once done save somewhere the string you will get, you will use it later.
- Fork the main SA repo from here https://github.com/Superalgos/Superalgos

![image](https://user-images.githubusercontent.com/38046064/161271112-5de2750e-c424-4c3a-a4de-0ea297815958.png)

![image](https://user-images.githubusercontent.com/38046064/161271342-3bea4556-66c6-450d-beb4-9765acc5e14c.png)

![image](https://user-images.githubusercontent.com/38046064/161272279-02754eb4-8572-404f-bdbd-987ddc4d458f.png)

Ok now you have everything you need to install SA and no need to do the above steps anymore.

The following steps must be done everytime you want to install SA.

Now, open a Terminal in Windows. If you have installed git then you have git bash, I use it.
In Windows Explorer create a folder where you want to save SA, then right click with mouse on its name and select Git Bash.
A new terminal window will open. If you prefer the integrated Windows Terminal, then use it, it's the same.

Now in the console you need to clone the repo, NOT the mian SA repo, but YOUR forked repo.

So in Terminal give this command:
git clone https://github.com/YOUR-GITHUB-USERNAME/Superalgos.git

You will see some strings telling you SA is downloading.
Once the process is complete enter in the Superalgos folder. In Terminal give this command: cd Superalgos

Now you should be in the Superalgos folder.
When you clone a repo usually you are in main/master branch (branches are different version of the same program, do a Google search in case you have doubs about github branches). To test the latest improvements (commits) you need to switch to develop branch. Give the following commands: git checkout develop

You should receive a message (in console) telling you switched the branch.

Now 2 more commands to give:
node setup -> It takes time, so wait a bit.

When finished give the following command:
node setupPlugins YOUR-GITHUB-USERNAME PERSONAL-ACCESS-TOKEN-STRING
(Please note there is a space between username and token)

When finished you are ready to run SA -> node platform

********************************************************************

I know it looks complex the first time but it really is not!

- It's a matter of installing 2 additional programs Git & Node and this is done just one time.
(By the way Git Desktop is not mandatory)
- Make a github account and generate a Personal Access Token also this is done only one time.
- Fork the main SA repo done only one time

Then whenever you want to install SA just open a terminal and do few steps:

- clone the repo 
- enter in the newly created folder (in this case is Superalgos)
- switch branch to develop
- node setup
- node setupPlugins username token (as explained above)

That's it.
Now just run SA using the command node platform in terminal

Let me kinow, if you still need help use telegram SA chat as it's faster

**Comment by BigJonMMXX** [comment]
Thank you for the lengthy explanation on INSTALLING superalgos. However, i am having trouble with UPDATING.

**Comment by 9808us** [comment]
> Thank you for the lengthy explanation on INSTALLING superalgos. However, i am having trouble with UPDATING.

When there are issues on updating SA from the Contribution tab usually it means you have changed something and GitHub signals a possible conflict.

There could be many other reasons but usually this has to do more with the way GitHub works that to a SA address/issue.

My advice is to just delete your old install and make a new one. If you need to keep your data, then everything is saved under the Platform folder.

**Comment by BigJonMMXX** [comment]
When you say delete my old install... that means delete the folder Superalgos (inside my GitRepos folder) - this would result in the deletion of ALL my settings and data. Plus this folder is 'synched' with my reposotroy on Giuthub, so does that get deleted as well...

i followed the README, as the Windows EXE left out many necessary steps and just didnt work.

**Comment by harrellbm** [comment]
If you are still struggling with this I can help walk you through steps to save your current install

**Comment by BigJonMMXX** [comment]
thank you for your reply, but i really cant face spending more hours on SA
at the moment. After getting it up and running and going thorough the
tutorials, i was told i still need to go through another tutorial that has
over 24 blocks/units... maybe i try FreqUI as it appears to get up and
running within 1% of the time needed for SA...
