### ISSUE TITLE
Welcome to Superalgos Tutorial - won't resume

### ISSUE THREAD

**Issue by krisj** [Superalgos/Superalgos#402]
MacOS, Chrome, all latest etc. fresh Superalgos install

following the getting started tutorial - when I "STOP" the tutorial, nothiing happnes when I try to click "Resume" on the ttorial node. Only "Start" works...

<img width="472" alt="Capto_Capture 2021-01-18_03-27-05_p m" src="https://user-images.githubusercontent.com/590660/104934254-d7cbda80-59a1-11eb-96dd-bfe0cbf7ef36.png">

Whats interesting, other tutorials can be started with "Resume" at this point.

**Comment by krisj** [comment]
Update: I've re-opened the workspace from the left drawer and re-ran the tutorial - it now seems to resume as expected. I will try to reproduce the non-resuming scenario and report back if I succeed.

**Comment by Luis-Fernando-Molina** [comment]
ok, thanks, also, that tutorial was finished today, the version for the next release, so you might want to update your codebase and do the latest version.

**Comment by krisj** [comment]
thanks, will try that

**Comment by Luis-Fernando-Molina** [comment]
For some of  the new features to work, you will need to check the new ReadMe at the develop branch, which includes, for instance the installation of the latest version of GIT and things like that.
