### ISSUE TITLE
Welcome to Superalgos Tutorial - Data Tasks node help doesn't seem to link correctly

### ISSUE THREAD

**Issue by krisj** [Superalgos/Superalgos#403]
<img width="863" alt="Capto_Capture 2021-01-18_03-44-39_p m" src="https://user-images.githubusercontent.com/590660/104936198-16fb2b00-59a4-11eb-97b2-309364947508.png">

following the guide - clicking on the node's Help button just opens the help with Node's hierarchy.

I noticed that many nodes don't link correctly to their help sections in fact. Also - are some nodes renamed recently? Some things don't seem to match.

Overall - trying to follow the welcome tutorial is fairly frustrating because half of the thing either don't work at all or don't seem to work correctly. Maybe reviewing the whole tutorial would be a good idea.

**Comment by krisj** [comment]
Update: after reopening the workspace and re-running the tutorial - the help button seems to link to the correct help section, however the problem remains - the node is called "Data Tasks" in the design space and "Data Mining" in the help section - very confusing.

**Comment by Luis-Fernando-Molina** [comment]
Part of the confusion is because the tutorial was being redone, in part while you were testing it. It was expanded to accommodate features of for the next release. If you find inconsistences or help pointing somewhere else, please tag @julian-molina that he is trying to finish with this task.
