### ISSUE TITLE
Welcome to Superalgos Tutorial - previous / Next broken

### ISSUE THREAD

**Issue by krisj** [Superalgos/Superalgos#404]
When clicking on previous/next buttons the tutorial seems to jump/skip some sections and gets confused with the order, sometimes sending me back to slide #1

**Comment by Luis-Fernando-Molina** [comment]
do you remember is this happens when you started with PLAY or RESUME? I think it is probably a bug for the resume option. I will check it now.

**Comment by Luis-Fernando-Molina** [comment]
Ok, I pushed a fix to develop, let me know if this happens again, and if not please close the issue.

**Comment by krisj** [comment]
Ok will pull the latest code and try it out...
