### ISSUE TITLE
Since Issue #313 Fix Live Candles are Generating with Same Values for Min, Max, High, Low values

### ISSUE THREAD

**Issue by Smidy13** [Superalgos/Superalgos#410]
## Context

**Operating System:** Ubuntu 20.04.1 LTS running on Raspberry PI 4 (4 GB), Google Chrome 87.0.4280.141 (64-bit)

**Software version:** today's develop branch 

**Workspace version:** Default Workspace.json (Getting Started Guide)

**Reproducible:** Yes, with "develop" branch

**Other Notes:** Running with minMemo and noBrowser flags

### 1. Explain what the problem seems to be.

I was previously affected by Issue #313 and therefore once I saw this had been closed I updated to the latest "develop" branch to test the fix.

Previously the HistoricOHLCV process would start hitting the Maximum Call Stack error around the ~850 loop. This is no longer occuring.

However, now a new fault presents where the live candles generated (when monitoring in Chart view) are being generated with the same Min, Max, High and Low values as the last candle.

If I manually update the code to change line 481 in the Superalgos/Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js file from: 

`setImmediate(checkHistoricOHLCV)`

back to:

`checkHistoricOHLCV()`

Then the live candles begin generating correctly once again.

If you stop and then restart all the Data Tasks then this will populate the missed candles correctly (up to an extent). However, again from when this is started the values appear incorrectly once more.

### 2. Clearly explain what you wish to accomplish.

As Data Mining Tasks are live running in the Live Trading Session I wish to be able to view candles being produced and added in real-time.

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

1) Git Clone the current develop branch using:
git clone -b develop https://github.com/Superalgos/Superalgos

2) Update the My Computer Network Node with IP address (as running frontend on different device)

3) Run All Project Data Task with the standard Binance BTC-UDST configuration and allow these to complete Exchange Raw Data, Candles Volumes and Resistances and Supports

4) Data up till the point where the Data Task was started appears fine, however any candles from after this point appear as the last gathered value with Max, Min, Open and Close all the same value.

![Screenshot 2021-01-19 155032](https://user-images.githubusercontent.com/77650800/104982067-bab10d80-5a6e-11eb-9541-56503fc3472d.png)

If you stop and then re-start the Data Mine Tasks then the candles generate correctly, but again any new candles which generate live are showing the zero values.

Highlighted yellow is the values which were showing as grey lines in the first screenshot, but the values are now correct after a stop and start.

Highlighted pink is the new values generated again showing as single lines with min, max, high and low all the same value.

![Screenshot 2021-01-19 160529](https://user-images.githubusercontent.com/77650800/104982756-2b0c5e80-5a70-11eb-9a87-f8715eaa3118.png)

### 4. Explain what is the result you expect from your actions.

Candles should continue to generate each minute correctly.

### 5. Explain what happens instead of the expected results.

Candles from after the Data Tasks were started appear as the last gathered value with Max, Min, Open and Close all the same value.

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

No errors seen, I have a feeling that the generation of the candles data is being tripped up as the checkHistoricOHLCV process now that this is running as setImmediate is not completed by the time the candles are sent to file.

## Attach relevant log files and error screenshots

Log files attached showing Data-Mine Data:

- Output of Data.json showing values before and after from Superalgos/Data-Storage/Project/Superalgos/Data-Mine/Masters/Candles-Volumes/Binance/BTC-USDT/Output/Candles/Multi-Period-Daily/01-min/2021/01/19

[Candles-Volumes - Multi-Period-Daily - Output - Candles - Multi-Period-Daily - 01-min - 2021.01.19.txt](https://github.com/Superalgos/Superalgos/files/5833477/Candles-Volumes.-.Multi-Period-Daily.-.Output.-.Candles.-.Multi-Period-Daily.-.01-min.-.2021.01.19.txt)

- Output of Data.json showing values before and after from Superalgos/Data-Storage/Project/Superalgos/Data-Mine/Masters/Exchange-Raw-Data/Binance/BTC-USDT/Output/Candles/One-Min/2021/01/19

[Exchange-Raw-Data - Candles - Output - One-Min - 2021.01.19.txt](https://github.com/Superalgos/Superalgos/files/5833469/Exchange-Raw-Data.-.Candles.-.Output.-.One-Min.-.2021.01.19.txt)

Log files attached showing Data-Mine Logs:

- Output of Superalgos/Log-Files/Project/Superalgos/Data-Mine/Masters/Exchange-Raw-Data/Binance/BTC-USDT/Logs/Historic-OHLCVs/D.2021.01.19.T.02.59.16

[Exchange-Raw-Data - HistoricOHLCVs - Loop.00000026.0000.txt](https://github.com/Superalgos/Superalgos/files/5833458/Exchange-Raw-Data.-.HistoricOHLCVs.-.Loop.00000026.0000.txt)

- Output of Superalgos/Log-Files/Project/Superalgos/Data-Mine/Masters/Candles-Volumes/Binance/BTC-USDT/Logs/Multi-Period-Daily/D.2021.01.19.T.02.59.17

[Candles-Volumes - Multi-Period-Daily - Loop.00000027.0000.txt](https://github.com/Superalgos/Superalgos/files/5833459/Candles-Volumes.-.Multi-Period-Daily.-.Loop.00000027.0000.txt)

- Output of Superalgos/Log-Files/Project/Superalgos/Data-Mine/Masters/Candles-Volumes/Binance/BTC-USDT/Logs/Multi-Period-Market/D.2021.01.19.T.02.59.17

[Candles-Volumes - Multi-Period-Market - Loop.00000027.0000.txt](https://github.com/Superalgos/Superalgos/files/5833461/Candles-Volumes.-.Multi-Period-Market.-.Loop.00000027.0000.txt)

**Comment by Luis-Fernando-Molina** [comment]
Thanks for reporting this bug. Will take care of it right now.

**Comment by 9808us** [comment]
Same for me, latest develop branch

![image](https://user-images.githubusercontent.com/38046064/105318425-cbbf6300-5bc3-11eb-8267-bae0ee24bbb1.png)

When running live , candles in the chart are not generated

**Comment by Luis-Fernando-Molina** [comment]
Ok, I pushed a fix to develop. Please try again and report any other issue. According to my tests, this is working well now.

**Comment by Smidy13** [comment]
I have tested with the latest develop branch and can confirm this is fixed.
