### ISSUE TITLE
Social Bot - Discord

### ISSUE THREAD

**Issue by teehanming** [Superalgos/Superalgos#4183]
## Context

*Complete and adjust the contents leaving the information that fits your case and deleting the information that doesn't.*

**Operating System:** Windows - WSL
**Software version:** today's develop branch 

**Workspace version:** My custom workspace 

**Reproducible:** the issue may 

### 1. Explain what the problem seems to be.

Discord Bot failed to send a test messege

### 2. Clearly explain what you wish to accomplish.

Connect the bot to discord server

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

1. Created a bot and add the token
2. add the bot into the server
3. giving administration permission to the bot
4. copy channel id
5. test send message -> fail

### 4. Explain what is the result you expect from your actions.

Success

### 5. Explain what happens instead of the expected results.

Fail

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

[ERROR] token must be set
httpInterface > Discord Bot > token must be set
TypeError: Cannot read properties of undefined (reading 'replace')
    at formatMessage (/mnt/e/Github/Superalgos/Projects/Social-Bots/SA/Bot-Modules/DiscordBot.js:89:45)
    at Object.sendMessage (/mnt/e/Github/Superalgos/Projects/Social-Bots/SA/Bot-Modules/DiscordBot.js:69:23)
    at /mnt/e/Github/Superalgos/Platform/Client/httpInterface.js:458:55
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

## Attach a video reproducing the issue

Attach video here.

## Attach relevant log files and error screenshots

![image](https://user-images.githubusercontent.com/65308523/172990211-003c530c-fdee-4e8a-9881-6f0358c3d5f3.png)

## Attach you custom workspace if any

Attach custom workspace here.

**Comment by BastianMuc** [comment]
Hi @teehanming ,

Please check the configuration of your Discord Bot if the parameters actually look like this:

```
{
"token": "DISCORD_BOT_AUTH_TOKEN_FROM_DEVELOPER_PORTAL",
"channelId": "CHANNEL_ID_FROM_DISCORD"
}
```

The tricky part is the comma (,) at the end of the token line. This required comma has not been added by default when a new Discord Bot was added until now. I'm submitting a fix for that, whereas you should be able to resolve the problem immediately by adding this comma by hand.

Hope this helps!
