### ISSUE TITLE
Exchange Raw Data Sensor Bot Instance // Error if Start date is removed

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#440]
**Operating System:** Windows 

**Software version:** today's develop branch 

**Workspace version:** default Workspace.json (Getting Started Guide)

**Reproducible:** the issue may be reproduced.

### 1. Explain what the problem seems to be.

If I remove the start date from Sensor Bot Instance under Exchange Raw Data and just leave {} ,
then I got an error in the console and candles are not fetched

### 2. Clearly explain what you wish to accomplish.

Remove the date should force the sensor bot to start from the first available candle

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

Workaround, set an arbitrary date far in the past (e.g. 2000-01-01)

### 4. Explain what is the result you expect from your actions.

Start from the very first candle

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

Not fetching candles, error in console, NaN values
See screenshot

![image](https://user-images.githubusercontent.com/38046064/105467368-e3671c00-5c95-11eb-981e-9d2294f2ea50.png)

Type your explanation here.

## Attach a video reproducing the issue

Attach video here.

## Attach relevant log files and error screenshots

Attach logs here.

## Attach you custom workspace if any

Attach custom workspace here.

**Comment by Smidy13** [comment]
Fixed under PR https://github.com/Superalgos/Superalgos/pull/871

There is a new function where if the startDate value is omitted it will set the start date to the epoch and then a recursive function will go backwards from the current date and determine the market start date.

**Comment by prepheadrus** [comment]
Hi,

Error like the picture occurs. How can I fix?


![2](https://user-images.githubusercontent.com/83468174/117017679-76cfd480-acfc-11eb-804c-8384c8c3d6c6.JPG)
![1](https://user-images.githubusercontent.com/83468174/117017690-79322e80-acfc-11eb-9538-2ba27cfe96dd.JPG)

**Comment by Smidy13** [comment]
Hi @prepheadrus 

The errors in your console are coming from the bot which creates the indicators. The code changes I pushed for this issue were related to the Exchange-Raw-Data (different bot) which appear to be running fine in your screenshots.

Are you able to raise a new issue for your bug? Make sure to put the timeframe you are running and which market (appears to be 2020-04 to 2020-05 and DOGE/USDT on Binance).

Also if possible include a share of your workspace.

Before raising your issue though make sure you are on the "develop" branch and have updated your code and also that you've tried clearing the Data-Storage directory for DOGE/USDT data and tried re-pulling the data from scratch if possible!

Hope this helps!
