### ISSUE TITLE
Backtesting // Run Request is stuck

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#477]
**Operating System:** Windows 

**Software version:** today's develop branch 

**Workspace version:** default Workspace.json (Getting Started Guide)

**Reproducible:** the issue may  be reproduced.

### 1. Explain what the problem seems to be.

See screenshot

![image](https://user-images.githubusercontent.com/38046064/105828317-47a21c80-5fc3-11eb-819f-5ee9460b57a7.png)

### 2. Clearly explain what you wish to accomplish.

Clicking on Run under Backtesting session before running the correspondenting task should allow you to run the strategy once the task is started too

### 5. Explain what happens instead of the expected results.

Click Run under Backtesting session but forgot to first run the Task
There is no way to start the backtesting session then, button Run Request Sent is stuck

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

Type your explanation here.

## Attach a video reproducing the issue

Attach video here.

## Attach relevant log files and error screenshots

Attach logs here.

## Attach you custom workspace if any

Attach custom workspace here.

**Comment by 9808us** [comment]
Here you can see that there is no process running
![image](https://user-images.githubusercontent.com/38046064/105835884-ba63c580-5fcc-11eb-98ea-809b860ddfe3.png)

![image](https://user-images.githubusercontent.com/38046064/105835902-c3549700-5fcc-11eb-8808-c244f087e6a6.png)

But if I expand the backtest nodeI can see the button is stuck
![image](https://user-images.githubusercontent.com/38046064/105835947-d4050d00-5fcc-11eb-96c7-06e4031b686b.png)

**Comment by Smidy13** [comment]
This is a separate issue to #683.

Bug Fix Commit submitted under https://github.com/Superalgos/Superalgos/pull/838/commits/d9f4fef9ae0ac3bc6c77fe655d5d88cb87113812
