### ISSUE TITLE
Add a maxRAM run parameter for setting max RAM usage

### ISSUE THREAD

**Issue by 9808us** [Superalgos/Superalgos#478]
**Is your feature request related to a problem? Please describe.**
Let people set max RAM with a parameter passed on run node
Currently if we use minMemo then max ram is set to a fixed value that we can not control

**Describe the solution you'd like**
run node maxRAM="set a desired value"

**Describe alternatives you've considered**
I can modify the run.js code but it will be overwritten when updating tha app

**Additional context**

**Comment by Luis-Fernando-Molina** [comment]
Your PR was merge, thanks!
