### ISSUE TITLE
Add Governance Menu on Top bar Platform

### ISSUE THREAD

**Issue by MarkTradeink** [Superalgos/Superalgos#4864]
**Is your feature request related to a problem? Please describe.**
After refactoring the "Plugin Workspaces" menu to "Sample Workspace" (Issue #382 ). I think the Governance Workspace should not be inside the same menu as the Sample Workspaces

**Describe the solution you'd like**
Add a new Menu Folder next to "Contributions" called Governance with direct access to the Governance Workspace

**Describe alternatives you've considered**
Move the Governance Workspace anywhere else...

**Comment by harrellbm** [comment]
This is a great idea! Let me know if you need help adding the menus.

**Comment by MarkTradeink** [comment]
After a conversation with Julian we decided not to add any new Menu and keep everything inside the actual Workspaces menu.
