### ISSUE TITLE
Copy trading tab - $SA 10.2M bounty!

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#4991]
# Context

The Social Trading App (STA) will be the ultimate solution for copy traders, as it will allow people to participate in the social trading network with minimal technical entry barriers. However, it will take a while to develop the STA to the point in which seamless copy trading is enabled.

In the meantime, there is another way in which we could bring technical entry barriers down while using the existing platform’s capabilities. 

The main objective is to drop the requirement to learn the UI, meaning that users should be able to run a copy trading session without doing the first three tutorials and learning the complexities of the platform.

This is the solution that will help us bootstrap a signal following crowd while the STA is developed.

# Solution

The solution Luis and I have in mind is a new tab, similar to the Contributions tab, where copy trading related inputs are captured via a web form. The system then passes on the captured data to the workspace, and interacts with the backend services replicating/reusing the existing infrastructure just like the Design Space does.

Conceptually, this new type of tab is an abstraction layer of the function that the Design Space provides. The Design Space offers complete control over everything users may do with the platform. These tabs help abstract the complexity of the Design Space to achieve very specific goals that may be determined by specific use cases.

# Use Case Definition

Once the platform is installed, a copy trading user launches the platform using a specific command:

`node platform Foundations Copy-Trading`

The command launches the platform with the Copy-Trading native workspace (to be created within the Foundations project).

The native workspace includes whatever is required for the Copy Trading tab to work as expected, and the said tab is open by default.

## Step 1: User Profile

Initially, the tab walks the user through the creation of his User Profile. To do that, it captures the required inputs, including GitHub username, preferences on the type of wallet (create a new one or load an existing one), etc. If the user creates a new wallet, the process will follow all the required processes, including providing the private key (for backup purposes), the wallet address, and so on.

The output is the basic User Profile.

## Step 2: Signal

Once the profile is created, the Copy Trading tab shows a different form where the user selects the signal provider and signal to follow. Upon selection, the platform loads the corresponding workspace.

The output is an update of the User Profile including all copy trading definitions (I.e.: all the nodes that map the signal, the definitions required for the required amount of token power to flow to the appropriate nodes, etc.).

## Step 3: Session

Now the tab captures the data required to setup the copy trading session: selection of tested exchanges (a drop down with specific exchanges that we have properly tested), selection of market (for instance, BTC against different USD stable coins — drop down defined by the signal provider), initial balance, exchange API key, and so on.

The output is an update of the workspace with all the captured data, saved as a user workspace, including the User Profile and corresponding references.

## Step 4: Operation

The tab offers a button to run the Data Mining operation. Once the data mining processes are at 100%, a new button is enabled to run the Copy Trading Session.

Once the session is running, the tab shows some basic control information that lets the user know if things are running properly or not. The tab also displays all relevant information about the trading session, including a log of each position and performance metrics (by position and episode).

# Requirements

For v1, the Copy Trading Tab will allow to follow a single signal — for simplicity. The user should be able to go back and select a different provider/signal combination at any point, and keep going with Steps 3 and 4.

In the future, the feature may be expanded to allow for multiple copy trading sessions.

# Bounty Notes

An analysis of the implementation is required, and is part of the job to be done. Please tag @Luis-Fernando-Molina for technical evaluation or questions. The job is considered finished once the spirit of the improvement is achieved: a new user should be able to do copy trading without learning anything.

The initial bounty is for $SA 10M, payable by Luis and myself. You are welcome to pledge more tokens for this bounty by posting a comment.

**Comment by Shiv-2712** [comment]
## Implementation Analysis:

**Strengths:**

1. **User-Friendly Approach:** The proposed Copy Trading Tab significantly reduces technical entry barriers. By using web forms and abstraction layers, users can navigate the platform without the need for extensive tutorials.

2. **Clear Workflow:** The step-by-step process (User Profile, Signal, Session, Operation) provides a clear and logical progression for users. Each step focuses on a specific aspect of copy trading, making it easy to understand and follow.

3. **Modular Design:** The approach of using tabs to capture specific copy trading inputs aligns well with the existing platform's capabilities. It builds upon the Design Space, which offers comprehensive control, while abstracting complexity for specific use cases.

4. **Flexible Signal Selection:** Allowing users to switch between signal providers and signals adds flexibility. This means users can adapt their copy trading strategy based on changing market conditions or their preferences.

**Areas for Consideration:**

1. **Security and Privacy:** When dealing with cryptocurrency wallets and private keys, security is paramount. It's crucial to implement robust encryption, authentication, and authorization mechanisms. Educating users on best practices for wallet security is also important.

2. **Error Handling and User Feedback:** The platform should provide clear and informative feedback to users at each step. This includes error messages, validation checks, and progress indicators. This ensures a smooth and frustration-free user experience.

3. **Data Validation and Sanitization:** It's imperative to validate and sanitize user inputs to prevent potential security vulnerabilities like SQL injection or other types of attacks.

4. **Documentation and Onboarding:** While the aim is to minimize the need for tutorials, there should still be easily accessible documentation or help resources for users who may require additional assistance.

5. **Scalability and Performance:** As the user base grows, the platform's backend services need to be capable of handling increased traffic. Scalability considerations should be factored into the system's architecture.

6. **Regulatory Compliance:** Depending on the region, there may be legal and regulatory requirements to consider, especially when dealing with financial transactions and cryptocurrencies.

7. **Monitoring and Analytics:** Implementing logging and analytics can provide valuable insights into user behavior and platform performance. This data can be used to improve the user experience and address any technical issues.

8. **Testing and Quality Assurance:** Rigorous testing, including unit tests, integration tests, and user acceptance testing, is crucial to ensure the platform functions reliably and securely.

Overall, the proposed implementation demonstrates a thoughtful and user-centric approach to simplifying copy trading. By addressing the areas for consideration, the platform can provide a secure, user-friendly, and reliable copy trading experience.
