### ISSUE TITLE
Grupo de Telegram gratuito (temporalmente) de alertas de trading.

### ISSUE THREAD

**Issue by TradingAlerts44** [Superalgos/Superalgos#5072]
﻿Hola! Somos un equipo de servicios de alertas de trading mediante análisis técnico y bots de inteligencia artificial en divisas como EUR/USD, AUD/CAD, entre otras y Cripto IDX (Binomo). 
Operamos con Binomo (CriptoIDX), TradingView, entre otras aplicaciones importantes. 

Este servicio consiste en brindarle alertas de calls y puts en temporalidad de 1 minuto de distintas divisas y en el activo Cripto IDX exclusivo de Binomo con una alta tasa de efectividad.

El mismo estará disponible gratuitamente hasta el Domingo 4/2/2024 23:59hs GMT-3, luego de este horario, el grupo pasará a ser privado y a ser de pago. 

Link de Telegram: https://t.me/TradingAlerts44

Desde ya muchas gracias.

**Comment by BastianMuc** [comment]
Spam
