### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by MEDJHAMraf** [Superalgos/Superalgos#5122]

**Comment by DaAlien81** [comment]
I have purchased sa token but im not able to see them on my user profile in superalgos. I have made a new profile and conected it to Trust Wallet. Also my user profile balace is not shown in Trust Wallet.

**Comment by julian-molina** [comment]
There is no message in the OP and the first comment refers to an issue I presume to have been clarified in the Tlegram support group, so I'm closing this issue.
