### ISSUE TITLE
Candles Fail to Load in Charts due to Capitilization 

### ISSUE THREAD

**Issue by Smidy13** [Superalgos/Superalgos#550]
## Context
**Operating System:** Ubuntu 20.04.1 LTS running on Raspberry PI 4 (4 GB), Google Chrome 88.0.4324.150 (Official Build) (64-bit)

**Software version:** today's develop branch 

**Workspace version:** Default Workspace.json (Getting Started Guide)

**Reproducible:** Yes, within the "develop" branch

**Other Notes:** Running with minMemo and noBrowser flags

### 1. Explain what the problem seems to be.

In the latest "develop" branch when following the tutorial and after downloading Binance data Candles will fail to show within the Chart view due to an issue with capitilization.

### 2. Clearly explain what you wish to accomplish.

After downloading data from the tutorial when switching to the Chart view the Candles should load as expected.

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

1. Git Clone the current develop branch using:
`git clone -b develop https://github.com/Superalgos/Superalgos`

2. Update the My Computer Network Node with IP address (as running frontend on different device)

3. Run All Project Data Task with the standard Binance BTC-UDST configuration and allow these to complete until Exchange Raw Data, Candles Volumes and Resistances and Supports all show 100% up to date.

4. Switch the to Chart view. No Candles load or display despite being turned On.

![Error - Candles Not Displaying](https://user-images.githubusercontent.com/77650800/107497431-7214ec00-6bf7-11eb-8fb3-6cbc2cde7837.PNG)

### 4. Explain what is the result you expect from your actions.

The Candles should display on the Chart.

### 5. Explain what happens instead of the expected results.

No Candles display.

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

The browser console clearly shows it is looking for the Data.json files using the Market name as "Binance". This is despite the files being stored within as "binance" in Lowercase in the Data-Storage directory.

![Google Chrome Developer Console Errors](https://user-images.githubusercontent.com/77650800/107497864-f10a2480-6bf7-11eb-9db3-e7d439df6d1b.PNG)

Manually changing the URL from "Binance" to "binance" then successfully resolves the Data.json.

![Failed Data JSON Request](https://user-images.githubusercontent.com/77650800/107499600-054f2100-6bfa-11eb-8576-143fde21dd1b.png)

![Successful Data JSON Request](https://user-images.githubusercontent.com/77650800/107499613-08e2a800-6bfa-11eb-938f-b2a59a48ca0f.png)

I'm suspecting the issue is caught up in the following commit: https://github.com/Superalgos/Superalgos/commit/463f8e0cdaca3793bb604980e896bee1e0184938

As I can see in the past in the following files the exchangeID was converted using the toLowerCase() command but now that we are using the codeName rather than Name this no longer occurs.

Projects/Superalgos/TS/Bot-Modules/Trading-Bot/Low-Frequency-Trading/APIs/ExchangeAPI.js
Projects/Superalgos/TS/Bot-Modules/Sensor-Bot/Exchange-Raw-Data/HistoricOHLCVs.js

**Comment by Luis-Fernando-Molina** [comment]
Thanks for reporting, a note was added to the Readme file with instructions on how to migarte from beta 8 to beta 9 to avoind this ussue.
