### ISSUE TITLE
References to Non-Existant Documentation Pages in Tutorials

### ISSUE THREAD

**Issue by nickspurry** [Superalgos/Superalgos#637]
## Context

**Software version:** Beta 8 - Master branch

**Workspace version:** Plugin -> Trading-System-Design-Tutorials 

**Reproducible:** the issue may be reproduced.

### 1. Explain what the problem seems to be.

A number of steps in the tutorials automatically open blank documentation pages. It appears that tutorial is trying to open the documentation page using the wrong name. The intended page can normally be found with a slightly different title by searching manually.

### 2. Clearly explain what you wish to accomplish.

The tutorial should open the intended page instead of creating a new blank page. 

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

1. Open Plugin -> Trading-System-Design-Tutorial
2. Run 3. Testing a Trading Idea Tutorial
3. Click Next until Bollinger Subchannels tutorial step is reached
4. Observe that Bollinger Channels documentation page is automatically opened, but documentation page is blank
5. Search "Bollinger Channels"
6. Open "Bollinger Channels - Masters Indicator" documentation page [this appears to be the page the tutorial step intended to open]

## Attach relevant log files and error screenshots
Screenshot of a different tutorial step with the same problem. There are multiple tutorial steps with the same issue.
![Superalgos Documentation Issue](https://user-images.githubusercontent.com/32992818/110230083-246f7300-7f5a-11eb-8293-8a8a01d291f5.PNG)

**Comment by julian-molina** [comment]
The Welcome tutorial has been revised for Beta 9. Would you be willing to verify if the issue has been solved?

**Comment by harrellbm** [comment]
@julian-molina I can confirm that the welcome Tutorials are fixed on a fresh install with the Beta 9 master branch.

**Comment by lokety** [comment]
Possibly related to this, I just installed Beta 9 and right from the first page of the tutorial, I'm getting:

> You need to reference a page at the docs at the config of this node. Use the docs property for that.

![image](https://user-images.githubusercontent.com/7494524/116551041-97d6a500-a94b-11eb-907c-a5dc9d3d3835.png)

**Comment by harrellbm** [comment]
@lokety This is indeed a related issue.  There is a patch for it on the develop branch already but it has not been merged into master yet.  You should be able to get tutorials working again with a quick browser refresh.

**Comment by Smidy13** [comment]
I just managed to recreate this in the latest build of "develop" and from what I could see the "project" variable in the TutorialSpace.js was set to "Ethereum" rather than "Superalgos". I've submitted commit https://github.com/Superalgos/Superalgos/pull/1035/commits/a182a2c3dfa90142fe2cf4a5001ad84bd3a6fd6e as a potential fix.

@harrellbm Do you have the reference to the patch which was on the "develop" branch alluded to in your previous comment? Was this the reference to just pushing F5 to refresh the page if you encountered this bug?

**Comment by Luis-Fernando-Molina** [comment]
Amazing job for spotting this @Smidy13 , I believe this bug wont bother us again now!
