### ISSUE TITLE
Docs context menu not working in Firefox

### ISSUE THREAD

**Issue by whtv** [Superalgos/Superalgos#664]
I understand we only support Chrome, which is fine, but for one reason or another one might need to use another browser. Right now the context menu doesn’t work at all in Firefox because Firefox doesn’t know the `Selection.baseNode` property.

Apparently `baseNode` is just an alias for `anchorNode`, though information on this is sparse and non-consistent. In Chrome the values are the same anyway and it works just fine with `anchorNode`. In Firefox the context menu works when using `anchorNode`, although it seems to not catch the right-click every time for some reason. Still better than breaking the docs-editing functionality altogether in Firefox I think, so I’m proposing to use `anchorNode`.

**Comment by Luis-Fernando-Molina** [comment]
It is not that we only support Chrome, it was just there was too little man power to fix all issues on all browsers, but now that more eyes are looking at this, maybe we can fix them and allow users to decide which browser they want to use. PR Merged.
