### ISSUE TITLE
Align Phase nodes (Sticking to go Straight Forward)

### ISSUE THREAD

**Issue by cozed-gh** [Superalgos/Superalgos#699]
**Is your feature request related to a problem? Please describe.**

It seems Phase nodes are built to just go "forward" from the previous phase node, resulting in doubling upon other nodes hiding behind it. It's not considered taking a spot.

![image](https://user-images.githubusercontent.com/76752164/111624748-5f8c6480-87ec-11eb-9367-85ce091865e1.png)
![image](https://user-images.githubusercontent.com/76752164/111624888-864a9b00-87ec-11eb-8cea-2f20dfe6eab4.png)

**Describe the solution you'd like**

Let the Phase-node be considered taking up a spot when branching out from another while un-pinned.

**Describe alternatives you've considered**

**Additional context**

**Comment by julian-molina** [comment]
Luis, this seems to be a long lasting technical debt... would be good to fix it in beta 10...
