### ISSUE TITLE
Zooming in the Designer

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Superalgos#7]
When zooming in or out, the view in the designer goes to the Workspace.

![Designer-Zoom](https://user-images.githubusercontent.com/13994516/63223466-3f329900-c1b6-11e9-8087-7218f1af413a.gif)

The way the zoom is currently behaving defeats the purpose of zooming in and out, which is being able to navigate from one section to another seamlessly: zoom out, pan a bit, zoom in, and there you are!. It is not currently possible to do that. The zoom operation is diminished to barely getting a bird's eye view...

**Comment by Luis-Fernando-Molina** [comment]
map implremented
