### ISSUE TITLE
Resource Loading Error 

### ISSUE THREAD

**Issue by harrellbm** [Superalgos/Superalgos#842]
## Before you open an issue

There are two requirements to open an issue:

1. You must first follow the [Troubleshooting Guide](https://docs.superalgos.org/suite-how-to-troubleshoot-an-issue.html)

2. If your issue hasn't been resolved by following the Troubleshooting Guide, then follow the guide on [How to Report an Issue](https://docs.superalgos.org/suite-how-to-report-an-issue.html).

## Context

*Complete and adjust the contents leaving the information that fits your case and deleting the information that doesn't.*

**Operating System:**  Linux Ubuntu 20

**Software version:** today's master branch.  Fresh install. 

**Workspace version:** default Workspace.json (Getting Started Guide).

**Reproducible:** the issue may not be reproducible.

### 1. Explain what the problem seems to be.

I believe it was the third time running a fresh install.  Noticed the welcome tutorial did not load correctly.

### 2. Clearly explain what you wish to accomplish.

Help find the source of this bug.

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

Cloned a fresh install of Superalgos from my fork.
Ran the install a few times with no issues.
Typed node run.

### 4. Explain what is the result you expect from your actions.

Things will load correctly.

### 5. Explain what happens instead of the expected results.

Everything loaded as normal until the welcome tutorial popped up displaying the "page not found" page.

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

I checked the console and saw 73 404 errors complaining about loading all kinds of different resources. 
![canvas-error](https://user-images.githubusercontent.com/55707292/116021335-405fce80-a605-11eb-893d-a075367da5fc.png)

I refreshed the browser and the tutorial loaded normally but this violation popped up in the console.
![canvas-violation](https://user-images.githubusercontent.com/55707292/116021470-7c932f00-a605-11eb-843a-14a746cb1723.png)

There where no errors in the terminal so this seems to be a browser side thing.

I was unable to reproduce the error on multiple attempts.

## Attach a video reproducing the issue

Attach video here.

## Attach relevant log files and error screenshots

Attach logs here.

## Attach you custom workspace if any

Attach custom workspace here.

**Comment by Smidy13** [comment]
The Resource Loading errors in the console are the Chart attempting to load the JSON's for the chart. However, as this is a fresh install the Data-Mining hasn't been done. Therefore these errors can be safely ignored.

Have looked into the Tutorial issue and found that the function to play the Tutorial was being called before the Workspace isInitialized flag is set to true. Therefore when the playTutorial was run it was exiting as the isInitialized flag was still false.

Have split function to play the Tutorials and placed this after the command where the workspace has been initialized.

Commit here: https://github.com/Smidy13/Superalgos/commit/9419d0b8495bee9cb5d3693a19f52c223084f0e2 (ignore the ProjectSchema changes, those changes are for a different function).

**Comment by harrellbm** [comment]
Sweet! That's awesome you found the bug.  Let me know if you need anything else with this.

**Comment by Luis-Fernando-Molina** [comment]
I will close the issue for now hopping no one experience this again. (fix currently only at the develop branch)
