### ISSUE TITLE
Tutorial Step Navigate to Map View option

### ISSUE THREAD

**Issue by harrellbm** [Superalgos/Superalgos#878]
**Is your feature request related to a problem? Please describe.**
There is currently no way to configure a tutorial step to zoom a user out to the map view.  This would be helpful within tutorial to give users a birds eye view of a workspace while explaining big picture ideas.

**Describe the solution you'd like**
An additional navigation option or switch would be a great way to add this to a steps configuration.

**Describe alternatives you've considered**
I have not dug into the code base in this area to have any ideas about implementation yet.

**Additional context**
Currently I am simply instructing the user of the tutorial to right click manually to enter the map view.  If they rush through and miss the cue to zoom back into the workspace the tutorial will continue but will never zoom them back in to the workspace.

**Comment by julian-molina** [comment]
This is a good idea. Most tutorials should start with an overview of the workspace, to set things clear for the user right from the start.

**Comment by Luis-Fernando-Molina** [comment]
In fact there is a way, since the MAP View has already a predefined keys shortcut, the same command to execute shorcuts like the one already used at tutorials CTRL + SHIFT + A should work for entering or exiting map view: Ctrl + Shift + M.

Let me know if that does not work to repone the issue.
