### ISSUE TITLE
is gui joke?

### ISSUE THREAD

**Issue by terr45tt** [Superalgos/Superalgos#883]
i see almost nothing, small icons with overlapping text, stupid useless effects, i use 14.4 inch  notebook and i cant read bubbles with text... if i resize page text is unreadable/overlapping.... keyboard shortcuts in conflict with browser shortcutt... impossible  control with touchpad.... and it is slow... there are glyphs with say norhing, without  "tip" text. I am sure this software is awesome but it is unusable because stupid ui... i am sure it would be betetr with flat straight UI, not this pseudo 90s unusable garbage...

**Comment by julian-molina** [comment]
You can build an alternate UI and we'll gladly incorporate it in the package.
