### ISSUE TITLE
Could not Push from UI: "fatal: could not read Username for 'https://github.com': No such device or address"

### ISSUE THREAD

**Issue by kizniche** [Superalgos/Superalgos#889]
## Context

**Operating System:** Linux (Raspberry Pi OS, latest updates) on Raspberry Pi 4

**Software version:** today's develop branch 

**Workspace version:** default Workspace.json (Getting Started Guide) 

**Reproducible:** the issue may be reproduced.

### 1. Explain what the problem seems to be.

I followed the docs in order to make a pull request through the UI but could not due to an error.

### 2. Clearly explain what you wish to accomplish.

Allow a successful push and pull request to be made through the UI.

### 3. Explain, step by step, what you've done to achieve the goal. The Team will follow these steps to reproduce the issue, so be precise.

1. Install latest Raspberry Pi OS (though latest Debian/Ubuntu may do)
2. Ensure up to date "sudo apt update && sudo apt upgrade"
3. Install Superalgos dependencies, namely Node.JS 14.
2. Fork Superalgos.
3. Clone with "git clone https://github.com/kizniche/Superalgos"
3. Run with "minMemo noBrowser"
4. Create GitHub API key with repo access.
5. Add user name and API key to GitHub API config in UI.
6. Set both the Current Branch and Contributions Branch to the ~~develop~~ plugins-docs branch.
7. Updated with "app.update"
8. Restart both the backend and the UI.
6. Make edit to docs.
7. Run "docs.save"
7. Run "app.contribute Grammatical and instructional fixes"
8. See error.

### 4. Explain what is the result you expect from your actions.

Successful push to my fork and a pull request appear on the main Superalgos repo.

### 5. Explain what happens instead of the expected results.

Failed push and errors returned.

### 6. Explain what errors you have found on-screen, on the browser console application, or in the ```Log-Files``` folder.

Upon running "app.contribute Grammatical and instructional fixes" I received the error:

#### Error Stack

```
 Error: Pushing to https://github.com/kizniche/Superalgos
fatal: could not read Username for 'https://github.com': No such device or address

    at GitExecutorChain.onFatalException (/home/pi/Superalgos/Client/node_modules/simple-git/src/lib/runners/git-executor-chain.js:61:87)
    at GitExecutorChain. (/home/pi/Superalgos/Client/node_modules/simple-git/src/lib/runners/git-executor-chain.js:52:28)
    at Generator.throw ()
    at rejected (/home/pi/Superalgos/Client/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

#### Error Code

```
Property errorCode not found at the placeholder object. 
```

#### Error Details

```
 {
    "task": {
        "commands": [
            "push",
            "origin",
            "develop",
            "--verbose",
            "--porcelain"
        ],
        "format": "utf-8"
    }
}
```

Additionally, when I clicked Next on the error page, it shows several more errors (screenshot below). Again, my github user name and API key were properly entered and successfully saved.

## Attach relevant log files and error screenshots

![screenshot-192 168 0 27_34248-2021 05 08-02_15_52](https://user-images.githubusercontent.com/838427/117529098-a5bba400-afa3-11eb-855b-b8d71e208041.png)

## Solution

How I solved this was by editing Superalgos/.git/config and changing:

```
[remote "origin"]
        url = https://github.com/kizniche/Superalgos
```

to

```
[remote "origin"]
        url = https://{MY_API_KEY}@github.com/kizniche/Superalgos.git
```

Where {MY_API_KEY} was my API key.

You can see PR #888 has two commits that were successfully pushed from the UI commands. The first commit was when I found the initial issue and the second was after searching for another issue in order to test if the issue presented itself if I reverted my config file change (it did).

**Comment by kizniche** [comment]
I just replicated the issue from scratch, in the process of creating #892 (on the proper branch), and it behaved exactly as I described previously.

**Comment by harrellbm** [comment]
@kizniche Have you still been having this issue?

**Comment by liteir** [comment]
I am having this exact issue today.

I am working on a Raspberry Pi 4.

**Comment by liteir** [comment]
App Error - Contribution Not Sent

Summary: There was a problem trying to send your contribution to your fork of the Superalgos repository, or from your fork to the Superalgos/Superalgos main repository.
Check the following section for details on what may have happened. After you fix the issue that prevented the App Contribute Command to run, you may try again.
Error Info
In the following section, you will find the information recorded when the error occurred.
 Note: You will only see the information if you opened this page as a result of the error actually occurring.
Error Message
The following is the Error Message of the Exception that occurred at the Client:
errorMessage
 Error: Pushing to https://github.com/liteir/Superalgos fatal: could not read Username for'https://github.com': No such device or address
Error Stack
The following is the Error Stack of the Exception that occurred at the Client:
errorStack
 Error: Pushing to https://github.com/liteir/Superalgos
fatal: could not read Username for 'https://github.com': No such device or address

    at Object.action (/home/pi/Superalgos/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)
    at PluginStore.exec (/home/pi/Superalgos/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)
    at /home/pi/Superalgos/node_modules/simple-git/src/lib/runners/git-executor-chain.js:95:45
    at new Promise ()
    at GitExecutorChain.handleTaskData (/home/pi/Superalgos/node_modules/simple-git/src/lib/runners/git-executor-chain.js:93:16)
    at GitExecutorChain. (/home/pi/Superalgos/node_modules/simple-git/src/lib/runners/git-executor-chain.js:77:46)
    at Generator.next ()
    at fulfilled (/home/pi/Superalgos/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error Code
The following is the Error Code of the Exception that occurred at the Client:
errorCode
 Note: Property errorCode not found at the placeholder object. This means that within the info received, this information is not available.
Error Details
The following are all the Error details of the Exception that occurred at the Client:
errorDetails
 {
    "task": {
        "commands": [
            "push",
            "origin",
            "plugins-docs",
            "--verbose",
            "--porcelain"
        ],
        "format": "utf-8"
    }
}

**Comment by liteir** [comment]
I got this while trying to go through the tutorial and submit my review. Have been trying to fix the issue for about an hour. I am calling it a day and will try again in the morning.

Again raspberry pi 4 running raspian os Lite

**Comment by Luis-Fernando-Molina** [comment]
Have you put your githubusername and token at this node's config?

![image](https://user-images.githubusercontent.com/9479367/140482293-6c19f9d7-4d3e-496b-ab99-126ab5200530.png)

**Comment by liteir** [comment]
Yes I did but I had to create the API because I could not find it.

![Github API](https://user-images.githubusercontent.com/82845387/140519555-127c5fe1-e70e-49c3-86e3-980df39d7f2f.PNG)
t.

**Comment by liteir** [comment]
I made sure I was in the Getting Started Workspace and tried searching for it in the docs and on the map. Finally found where I could create it and did. Is it hidden in some other node?

**Comment by ozichris** [comment]
same issue.

**Comment by NAmorim** [comment]
Is this issue still valid in the latest release?

**Comment by kizniche** [comment]
I have not tested with the latest release as of today
