### ISSUE TITLE
1K Stars

### ISSUE THREAD

**Issue by Ubiquitous** [Superalgos/Superalgos#897]
Not really an issue, but a **BIG CONGRATULATIONS** on getting **1K** stars! 

It was cool watching it change from 999 to 1K when I clicked it :) Anyway, keep up the great work and if you're interested in some new header graphics for Superalgos I got some ideas; not sure where you submit ideas and what not.

> Superalgo is worth a thousand stars.

~ Cheers!

**Comment by julian-molina** [comment]
How cool is that?!

Join us in the [UX/UI Design](https://t.me/superalgosuxui) group and tell us what you're thinking in regards to graphics!

**Comment by Luis-Fernando-Molina** [comment]
Thanks a lot!
