### ISSUE TITLE
User Experience

### ISSUE THREAD

**Issue by AnimateDread** [Superalgos/Superalgos#942]
The code is beautiful and solid, the hierarchy is clean, but this piece of art is still unuseable because of the app. I am a power user, ex shell and obj-c programmer, yet after weeks of toying around, I still can't plot the MACD on a chart, still unable to launch a backtest, I can't work with the charting space at all (it takes about 5 min of trying to do something with it to break it) let alone test any ideas.

Selecting indicators and seeing how they react on the chart/backtesting takes about 5 min on cryptohopper.

If somebody can come up with an useable UI then I think you'll start seeing true adoption and trading systems development.
I'm wondering how useful is machine learning if just creating and testing an ema crossover strategy is as complex as coding a game in assembly ?

**Comment by Luis-Fernando-Molina** [comment]
Thanks for the feedback. I wish I had more time to dedicate to the UI to improve the UX. I am not very proud of the state of many parts of the system, but time is limited. It will probably improve as more people jump in and contribute. In the meantime, doing all the tutorials is the only thing that can help avoid frustrations when things don't work as expected. Having all these challenges is the reason why this is still on beta.
